/* ══════════════════════════════════════════════════════════════════════
   DigiKitPro — product image gallery (js/gallery.js)
   ----------------------------------------------------------------------
   THE BUG THIS FIXES
   Product pages used to swap the big image by writing `img.src` alone.
   The main <img> also carried a `srcset` built from image #1 (card crop
   + cover), and in the HTML image-selection algorithm a matching srcset
   candidate ALWAYS wins over the src attribute — so every click updated
   the attribute while the browser kept painting image #1. The thumbnails
   looked dead. On top of that the swap waited on a hidden preloader's
   `onload` with no `onerror` and no timeout, so any hiccup there meant
   "nothing happens", permanently, and the tile had already been marked
   active for a picture that never arrived.

   This module therefore owns the WHOLE source set: srcset, sizes, src,
   width, height and alt are always rewritten together, from the
   thumbnail's own `data-full-image`. The card crop is only ever used for
   the small tile — an enlarged thumbnail is never passed off as the main
   image when the full-size file exists.

   RULES IT KEEPS
   • Vanilla ES5, no libraries, no build step, one file.
   • Self-contained: it only ever touches [data-product-gallery]. Search,
     category filters, nav, translation, Payhip and Pinterest behaviour in
     js/main.js are neither rewritten nor shadowed.
   • Works on every product page automatically by reading the images that
     are already in the markup. No product lists, no per-product exceptions.
   • Progressive enhancement: with JS off the page still shows the real
     cover, the real file behind every tile and the Pin button. Nothing is
     hidden behind a script that failed to run.
   • A click never navigates, never reloads and never moves the page.
   ══════════════════════════════════════════════════════════════════════ */
(function () {
  "use strict";

  var $ = function (s, c) { return (c || document).querySelector(s); };
  var $$ = function (s, c) { return Array.prototype.slice.call((c || document).querySelectorAll(s)); };

  /* Every hook is optional: the generated markup and the pages already out
     in the wild (data-gal-* / .gal-thumb / data-full) both light up. */
  var MAIN_SEL = "#product-main-image, [data-gallery-main], [data-gal-main]";
  var THUMB_SEL = "[data-gallery-thumb], [data-gal-thumb], .product-gallery-thumb, .gal-thumb";

  var CHEV_L = '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m15 6-6 6 6 6"/></svg>';
  var CHEV_R = '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 6 6 6-6 6"/></svg>';
  var CROSS = '<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg>';

  /* ── helpers ──────────────────────────────────────────────────────────── */
  function attr(el, names) {
    if (!el) return "";
    for (var i = 0; i < names.length; i++) {
      var v = el.getAttribute(names[i]);
      if (v === null || v === undefined) continue;
      v = String(v).replace(/^\s+|\s+$/g, "");
      if (v) return v;
    }
    return "";
  }
  function num(v, fallback) {
    var n = parseInt(v, 10);
    return isFinite(n) && n > 0 ? n : fallback;
  }
  function baseName(u) { return String(u || "").split("#")[0].split("?")[0].replace(/^.*\//, "").toLowerCase(); }
  /* Pinterest needs an absolute URL; a page generated by hand may only have a
     relative one, so the frame's own file is resolved rather than abandoned. */
  function abs(u) {
    if (!u || /^data:/.test(u)) return "";
    try { return new URL(u, location.href).href; } catch (e) { return /^https?:/.test(u) ? u : ""; }
  }
  function clampIndex(i, n) { if (!n) return 0; i = i % n; return i < 0 ? i + n : i; }
  function tag(el) { return el && el.tagName ? el.tagName.toUpperCase() : ""; }
  function reduced() {
    try { return !!(window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches); } catch (e) { return false; }
  }
  /* Ask before spending the visitor's bandwidth: warming is a courtesy, not
     a requirement, and a metered connection declines politely. */
  function conserveData() {
    try {
      var c = navigator.connection || navigator.mozConnection || navigator.webkitConnection;
      return !!(c && (c.saveData === true || (c.effectiveType && /(^|[^a-z])2g/.test(c.effectiveType))));
    } catch (e) { return false; }
  }
  function whenIdle(fn) {
    if (window.requestIdleCallback) { try { window.requestIdleCallback(fn, { timeout: 3000 }); return; } catch (e) {} }
    setTimeout(fn, 1200);
  }
  function isTypingTarget(el) {
    if (!el || !el.tagName) return false;
    var t = tag(el);
    return t === "INPUT" || t === "TEXTAREA" || t === "SELECT" || el.isContentEditable === true;
  }
  /* Only a fallback for a record with no alt text written: the page's own H1. */
  function productName() {
    var h = $(".pdp-info h1") || $(".pdp h1");
    return h ? String(h.textContent || "").replace(/^\s+|\s+$/g, "") : "product image";
  }

  /* ── the "already have it" cache ─────────────────────────────────────────
     One place decides whether a file is known-good, so a click can paint
     instantly and the preloader never asks for the same URL twice. */
  var loadedOK = {};
  function warm(src) {
    if (!src || loadedOK[src]) return;
    var im = new Image();
    im.decoding = "async";
    im.onload = function () { loadedOK[src] = 1; };
    im.src = src;
  }

  /* ── one gallery ──────────────────────────────────────────────────────── */
  function setup(gallery) {
    if (!gallery || gallery.__dkpGal) return;
    var mainImage = $(MAIN_SEL, gallery);
    if (!mainImage) return;                       /* not a product page */
    gallery.__dkpGal = 1;

    var thumbEls = $$(THUMB_SEL, gallery);

    /* Items come from the DOM, so a product with 1 image and a product with
       9 are the same code path. A tile with no full-size reference shows its
       own file (its href, then its img src) — never another item's picture. */
    var items = [];
    for (var i = 0; i < thumbEls.length; i++) {
      var el = thumbEls[i];
      var tile = $("img", el);
      var full = attr(el, ["data-full-image", "data-full"]) || (tile ? attr(tile, ["data-full-image", "data-full"]) : "");
      if (!full && tag(el) === "A") full = el.getAttribute("href") || "";
      if (!full && tile) full = tile.getAttribute("src") || "";
      if (!full) full = mainImage.getAttribute("src") || "";
      if (!full) continue;
      items.push({
        thumb: el,
        tile: tile,
        full: full,
        srcset: attr(el, ["data-srcset-image", "data-srcset"]),
        sizes: attr(el, ["data-sizes-image", "data-sizes"]),
        alt: attr(el, ["data-alt"]) || (tile ? tile.getAttribute("alt") || "" : ""),
        w: num(attr(el, ["data-w", "data-width"]), tile ? num(tile.getAttribute("width"), 0) : 0),
        h: num(attr(el, ["data-h", "data-height"]), tile ? num(tile.getAttribute("height"), 0) : 0),
        pin: attr(el, ["data-pin-media"]),
        index: items.length
      });
    }
    if (!items.length) {
      /* No tiles in the markup (single-image product): the cover alone is a
         one-item gallery, which still earns the zoom affordance. */
      var coverSrc = mainImage.getAttribute("src") || "";
      if (!coverSrc) return;
      items.push({
        thumb: null, tile: null, full: coverSrc, srcset: "", sizes: "",
        alt: mainImage.getAttribute("alt") || "",
        w: num(mainImage.getAttribute("width"), 0), h: num(mainImage.getAttribute("height"), 0),
        pin: attr(mainImage, ["data-pin-media"]), index: 0
      });
    }
    var total = items.length;
    var many = total > 1;
    var current = 0;

    /* A srcset belonging to a DIFFERENT image is the original bug. Unless the
       generator gave an item its own srcset, the markup's srcset is adopted
       only while it still names that item's own file. */
    var markupSrcset = mainImage.getAttribute("srcset") || "";
    for (var k = 0; k < total; k++) {
      if (items[k].srcset) continue;
      items[k].srcset = (k === 0 && markupSrcset && markupSrcset.indexOf(baseName(items[k].full)) >= 0) ? markupSrcset : "";
      if (!items[k].srcset) items[k].sizes = "";
    }

    var figure = tag(mainImage.parentNode) === "FIGURE" ? mainImage.parentNode : null;
    var swiped = 0;
    var lightbox = null;
    var displayed = null;   /* what is on screen right now, known good */
    var previous = null;    /* what to go back to if a swap fails        */
    var pending = "";       /* the URL a swap is waiting on              */

    /* ── chrome: prev / next / counter. Injected when the markup has none,
        so pages deployed before this file still get the controls. ──────── */
    var prevBtn = $("[data-gallery-prev]", gallery);
    var nextBtn = $("[data-gallery-next]", gallery);
    var counter = $("[data-gallery-count]", gallery);
    if (many && figure) {
      if (!prevBtn) prevBtn = addControl(figure, "gal-nav gal-nav-prev", "data-gallery-prev", "Previous product image", CHEV_L);
      if (!nextBtn) nextBtn = addControl(figure, "gal-nav gal-nav-next", "data-gallery-next", "Next product image", CHEV_R);
      if (!counter) {
        counter = document.createElement("span");
        counter.className = "gal-count";
        counter.setAttribute("data-gallery-count", "");
        counter.setAttribute("aria-live", "polite");
        figure.appendChild(counter);
      }
    }
    function addControl(parent, cls, hook, label, icon) {
      var b = document.createElement("button");
      b.type = "button";
      b.className = cls;
      b.setAttribute(hook, "");
      b.setAttribute("aria-label", label);
      b.innerHTML = icon;
      parent.appendChild(b);
      return b;
    }
    gallery.setAttribute(many ? "data-gallery-count-total" : "data-gallery-single", many ? String(total) : "1");

    /* ── paint one item into the main frame ──────────────────────────────── */
    function paint(item) {
      if (item.srcset) {
        mainImage.setAttribute("srcset", item.srcset);
        if (item.sizes) mainImage.setAttribute("sizes", item.sizes); else mainImage.removeAttribute("sizes");
      } else {
        mainImage.removeAttribute("srcset");
        mainImage.removeAttribute("sizes");
      }
      mainImage.setAttribute("src", item.full);
      if (item.alt) mainImage.setAttribute("alt", item.alt);
      if (item.w && item.h) { mainImage.setAttribute("width", item.w); mainImage.setAttribute("height", item.h); }
      /* Keep the Pinterest save target in sync with what is on screen: the
         visible artwork is the one a pin must capture. */
      var pinMedia = item.pin || abs(item.full);
      if (pinMedia) {
        mainImage.setAttribute("data-pin-media", pinMedia);
        var anchor = figure ? $("[data-pin-anchor]", figure) : null;
        if (anchor) {
          try {
            var u = new URL(anchor.href, location.href);
            u.searchParams.set("media", pinMedia);
            anchor.href = u.toString();
          } catch (e) { /* keep the first image's pin target */ }
        }
      }
    }

    function showImage(index, opts) {
      opts = opts || {};
      index = clampIndex(index, total);
      var item = items[index];
      if (!item || !item.full) return;

      /* 1. the tiles follow the picture */
      for (var n = 0; n < total; n++) {
        var t = items[n].thumb;
        if (!t) continue;
        if (n === index) { t.classList.add("active"); t.setAttribute("aria-current", "true"); }
        else { t.classList.remove("active"); t.removeAttribute("aria-current"); }
      }

      /* 2. the main image — skipped when it already shows this exact file, so
         the first paint on load never re-downloads or flickers. If an older
         cached js/main.js writes `src` behind our back, our srcset travels
         with it and still wins, so the picture never drifts. */
      if (!displayed && !opts.alreadyShown) {
        previous = null;
        displayed = item;
        paint(item);
      } else if (displayed && displayed.full !== item.full) {
        previous = displayed;
        displayed = item;
        paint(item);
        pending = item.full;
        /* While a swap is in flight the gallery owns the failure path, so the
           site-wide "coming soon" fallback stays out of it. */
        mainImage.setAttribute("data-fbk", "1");
        if (!loadedOK[item.full]) probe(item.full);
      }
      if (opts.alreadyShown && !displayed) displayed = item;

      current = index;
      gallery.setAttribute("data-current-index", String(index));
      if (counter) counter.textContent = (index + 1) + " / " + total;
      /* The frame is activatable, so it needs an accessible name — and that
         name has to keep describing the artwork, not only the button act. */
      mainImage.setAttribute("aria-label",
        (many ? "Product image " + (index + 1) + " of " + total + ", open full size: " : "Open full size: ")
        + (item.alt || productName()));
      warmNeighbors(index);
      if (!opts.noScroll) keepTileInView(index);
      if (!opts.silent) {
        try {
          gallery.dispatchEvent(new CustomEvent("dkp:gallerychange", { bubbles: true, detail: { index: index, total: total, src: item.full } }));
        } catch (e) { /* nothing on the site depends on this yet */ }
      }
    }

    /* 3. a failed swap puts back what the visitor was looking at: no broken
       image frame, no placeholder, nothing else on the page disturbed. Two
       independent signals watch the same swap — the frame's own error event
       and a side probe — so the rollback never depends on one of them
       arriving. Either one, first come. */
    function failBack() {
      if (!pending) return;
      pending = "";
      if (!previous) return;
      displayed = previous;
      previous = null;
      paint(displayed);
    }
    function probe(url) {
      var im = new Image();
      im.decoding = "async";
      im.onload = function () { loadedOK[url] = 1; };
      im.onerror = function () { if (pending === url) failBack(); };
      im.src = url;
    }
    mainImage.addEventListener("error", failBack);
    mainImage.addEventListener("load", function () {
      if (pending && baseName(mainImage.getAttribute("src")) === baseName(pending)) pending = "";
    });

    function warmNeighbors(index) {
      if (!many || conserveData()) return;
      warm(items[clampIndex(index + 1, total)].full);
      warm(items[clampIndex(index - 1, total)].full);
    }

    /* Keep the chosen tile inside the strip WITHOUT moving the page: the
       container is scrolled by hand — scrollIntoView would drag the window
       along with it, and the visitor would lose their place. */
    function keepTileInView(index) {
      var item = items[index];
      if (!item || !item.thumb) return;
      var strip = item.thumb.parentNode;
      if (!strip || strip.scrollWidth <= strip.clientWidth + 4) return;
      var left = item.thumb.offsetLeft - (strip.clientWidth - item.thumb.offsetWidth) / 2;
      left = Math.max(0, Math.min(strip.scrollWidth - strip.clientWidth, left));
      if (reduced() || !strip.scrollTo) { strip.scrollLeft = left; return; }
      try { strip.scrollTo({ left: left, behavior: "smooth" }); } catch (e) { strip.scrollLeft = left; }
    }

    /* ── tiles: click, and nothing else ─────────────────────────────────── */
    thumbEls.forEach(function (el, idx) {
      if (tag(el) === "A") { el.setAttribute("role", el.getAttribute("role") || "button"); el.setAttribute("title", el.getAttribute("title") || "Show this image in the main frame"); }
      el.addEventListener("click", function (ev) {
        /* Buttons do not navigate; the guards are for a tile still nested in
           a link, so a tap can never reload the page, open the raw image, or
           fire the product card / Pinterest link around it. */
        ev.preventDefault();
        ev.stopPropagation();
        showImage(idx);
      });
      if (tag(el) === "A") {
        el.addEventListener("keydown", function (ev) {
          if (ev.key === "Enter" || ev.key === " " || ev.key === "Spacebar") { ev.preventDefault(); ev.stopPropagation(); showImage(idx); }
        });
      }
    });

    /* ── prev / next ─────────────────────────────────────────────────────── */
    function bindNav(btn, delta) {
      if (!btn || btn.__dkpGalNav) return;
      btn.__dkpGalNav = 1;
      btn.addEventListener("click", function (ev) {
        ev.preventDefault();
        ev.stopPropagation();
        showImage(current + delta);
      });
    }
    bindNav(prevBtn, -1);
    bindNav(nextBtn, 1);

    /* ── keyboard. The arrow handler lives ON THE GALLERY, so it can never be
       mistaken for the search field's or a text box's keys, and it does
       nothing while the lightbox is open (that owns the keyboard). ──────── */
    gallery.addEventListener("keydown", function (ev) {
      if (ev.defaultPrevented || isTypingTarget(ev.target)) return;
      if (lightbox && lightbox.open) return;
      var step = 0;
      if (ev.key === "ArrowLeft" || ev.key === "Left") step = -1;
      else if (ev.key === "ArrowRight" || ev.key === "Right") step = 1;
      else if (many && (ev.key === "Home" || ev.key === "End")) { ev.preventDefault(); showImage(ev.key === "Home" ? 0 : total - 1); return; }
      if (!step) return;
      ev.preventDefault();
      showImage(current + step);
    });

    /* ── swipe (touch) ──────────────────────────────────────────────────────
       A deliberate horizontal flick changes the image. Everything else — a
       tap, a vertical scroll, a long press — is left exactly as the browser
       would handle it, so tapping tiles and scrolling the page keep working. */
    function attachSwipe(el, onFlick) {
      if (!el) return;
      var x0 = 0, y0 = 0, t0 = 0, armed = false;
      el.addEventListener("touchstart", function (ev) {
        var t = ev.changedTouches && ev.changedTouches[0];
        if (!t || (ev.touches && ev.touches.length > 1)) { armed = false; return; }
        x0 = t.clientX; y0 = t.clientY; t0 = Date.now(); armed = true;
      }, { passive: true });
      el.addEventListener("touchend", function (ev) {
        if (!armed) return;
        armed = false;
        var t = ev.changedTouches && ev.changedTouches[0];
        if (!t) return;
        var dx = t.clientX - x0, dy = t.clientY - y0, dt = Date.now() - t0;
        if (Math.abs(dx) < 28 || Math.abs(dx) < Math.abs(dy) * 1.6 || dt > 800) return;
        if (onFlick) onFlick();
        showImage(current + (dx < 0 ? 1 : -1));
      }, { passive: true });
    }
    attachSwipe(mainImage, function () { swiped = Date.now(); });

    /* ── lightbox ────────────────────────────────────────────────────────── */
    function buildLightbox() {
      var root = document.createElement("div");
      root.className = "dkp-lb";
      root.setAttribute("role", "dialog");
      root.setAttribute("aria-modal", "true");
      root.setAttribute("aria-label", "Product image viewer");
      root.setAttribute("tabindex", "-1");
      root.hidden = true;
      root.innerHTML =
        '<div class="dkp-lb-bar">' +
          '<span class="dkp-lb-count" data-lb-count></span>' +
          '<button type="button" class="dkp-lb-x" data-lb-close aria-label="Close product image viewer">' + CROSS + '</button>' +
        '</div>' +
        (many ? '<button type="button" class="dkp-lb-nav dkp-lb-prev" data-lb-prev aria-label="Previous product image">' + CHEV_L + '</button>' +
                '<button type="button" class="dkp-lb-nav dkp-lb-next" data-lb-next aria-label="Next product image">' + CHEV_R + '</button>' : '') +
        '<div class="dkp-lb-stage" data-lb-stage><img class="dkp-lb-img" alt="" decoding="async"></div>' +
        '<p class="dkp-lb-hint">' + (many ? 'Arrow keys change image · Esc closes' : 'Esc closes') + '</p>';
      document.body.appendChild(root);

      var lb = { root: root, img: $(".dkp-lb-img", root), count: $("[data-lb-count]", root), open: false, focusBack: null, keys: null };

      lb.render = function () {
        var item = items[current];
        if (!item) return;
        lb.img.removeAttribute("srcset");
        lb.img.setAttribute("src", item.full);
        lb.img.setAttribute("alt", item.alt || "");
        if (lb.count) lb.count.textContent = many ? (current + 1) + " of " + total : "";
      };
      function step(delta) { showImage(current + delta, { noScroll: true }); lb.render(); }

      function on(sel, fn) { $$(sel, root).forEach(function (b) { b.addEventListener("click", function (ev) { ev.preventDefault(); ev.stopPropagation(); fn(); }); }); }
      on("[data-lb-prev]", function () { step(-1); });
      on("[data-lb-next]", function () { step(1); });
      on("[data-lb-close]", function () { lb.close(); });
      /* a click outside the artwork closes it; a click on the artwork does not */
      root.addEventListener("click", function (ev) {
        if (ev.target === root || (ev.target.className && String(ev.target.className).indexOf("dkp-lb-stage") >= 0)) lb.close();
      });
      attachSwipe($(".dkp-lb-stage", root), null);

      lb.show = function () {
        if (lb.open) return;
        lb.open = true;
        lb.focusBack = document.activeElement;
        root.hidden = false;
        lockScroll(true);
        lb.render();
        requestAnimationFrame(function () { root.classList.add("is-open"); });
        var first = $("[data-lb-close]", root);
        if (first && first.focus) { try { first.focus(); } catch (e) {} }
        lb.keys = function (ev) {
          if (ev.key === "Escape" || ev.key === "Esc") { ev.preventDefault(); lb.close(); return; }
          if (ev.key === "ArrowLeft" || ev.key === "Left") { ev.preventDefault(); step(-1); return; }
          if (ev.key === "ArrowRight" || ev.key === "Right") { ev.preventDefault(); step(1); return; }
          if (ev.key === "Tab") {
            var f = $$("button, [href], input, [tabindex]:not([tabindex='-1'])", root).filter(function (n) { return !n.disabled; });
            if (!f.length) return;
            var a = f[0], z = f[f.length - 1];
            if (ev.shiftKey && document.activeElement === a) { ev.preventDefault(); z.focus(); }
            else if (!ev.shiftKey && document.activeElement === z) { ev.preventDefault(); a.focus(); }
          }
        };
        document.addEventListener("keydown", lb.keys, true);
      };

      lb.close = function () {
        if (!lb.open) return;
        lb.open = false;
        root.classList.remove("is-open");
        document.removeEventListener("keydown", lb.keys, true);
        lockScroll(false);
        setTimeout(function () { if (!lb.open) root.hidden = true; }, reduced() ? 0 : 160);
        if (lb.focusBack && lb.focusBack.focus) { try { lb.focusBack.focus(); } catch (e) {} }
      };
      return lb;
    }

    function openLightbox() {
      if (!lightbox) lightbox = buildLightbox();
      lightbox.show();
    }

    function lockScroll(on) {
      var d = document.documentElement, b = document.body;
      if (on) {
        var gap = d.clientWidth ? (window.innerWidth - d.clientWidth) : 0;
        d.classList.add("dkp-lb-open");
        if (gap > 0 && b) b.style.paddingRight = gap + "px";
      } else {
        d.classList.remove("dkp-lb-open");
        if (b) b.style.paddingRight = "";
      }
    }

    /* The main frame becomes a real button for keyboard and screen-reader
       users; it looks identical — the CSS still draws a plain picture. */
    mainImage.setAttribute("tabindex", "0");
    mainImage.setAttribute("role", "button");
    mainImage.setAttribute("data-gallery-zoom", "");
    mainImage.addEventListener("click", function (ev) {
      if (ev.target !== mainImage) return;               /* the Save overlay owns its clicks */
      if (tag(ev.target) === "A" || tag(ev.target) === "BUTTON") return;
      if (Date.now() - swiped < 500) return;              /* that was a flick, not a tap */
      ev.preventDefault();
      ev.stopPropagation();
      openLightbox();
    });
    mainImage.addEventListener("keydown", function (ev) {
      if (ev.key === "Enter" || ev.key === " " || ev.key === "Spacebar") { ev.preventDefault(); ev.stopPropagation(); openLightbox(); }
    });

    /* ── preload after the page itself is done, on idle time ───────────────
       Every gallery image is small (webp, ≤ 1200px), so 6 of them is a
       rounding error; beyond that only the neighbour of the current frame is
       fetched, so a 12-tile product never bulk-loads on page open. Tiles stay
       lazy: this warms what a click will need, not what is already visible. */
    function preloadAll() {
      if (conserveData()) return;
      var cap = Math.min(total, 6);
      for (var n = 0; n < cap; n++) warm(items[clampIndex(current + n, total)].full);
      if (total > cap) warm(items[clampIndex(current + 1, total)].full);
    }
    if (document.readyState === "complete") whenIdle(preloadAll);
    else window.addEventListener("load", function () { whenIdle(preloadAll); }, { once: true });

    /* ── adopt the frame that is already painted ────────────────────────── */
    var painted = baseName(mainImage.getAttribute("src"));
    var start = 0;
    for (var p = 0; p < total; p++) if (baseName(items[p].full) === painted) { start = p; break; }
    var wanted = clampIndex(num(attr(gallery, ["data-current-index"]), start), total);
    if (wanted === start) showImage(start, { alreadyShown: true, noScroll: true, silent: true });
    else showImage(wanted, { noScroll: true, silent: true });

    /* Public handle, so another module or a QA script can drive the gallery
       without reaching into private state. */
    gallery.__dkpGallery = {
      total: total,
      index: function () { return current; },
      show: function (n) { showImage(n); },
      next: function () { showImage(current + 1); },
      prev: function () { showImage(current - 1); },
      openLightbox: openLightbox,
      closeLightbox: function () { if (lightbox) lightbox.close(); },
      lightboxOpen: function () { return !!(lightbox && lightbox.open); },
      mainImage: mainImage,
      thumbs: thumbEls
    };
  }

  /* ── boot ────────────────────────────────────────────────────────────────
     Safe whenever it runs. A page without a product gallery costs two
     querySelectorAll calls and returns; nothing else on the page is touched. */
  function initProductGallery() {
    /* A dialog left behind by the retired inline gallery is not ours to keep:
       removing it stops one click opening two overlays while older cached
       copies of js/main.js are still in circulation. */
    var stale = $$("dialog.gal-light");
    for (var i = 0; i < stale.length; i++) { try { stale[i].parentNode.removeChild(stale[i]); } catch (e) {} }

    $$("[data-product-gallery]").forEach(setup);
    /* Fallback for pages generated before this module existed. */
    $$(".pdp-media").forEach(function (el) {
      if (!el.hasAttribute("data-product-gallery")) el.setAttribute("data-product-gallery", "");
      setup(el);
    });
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", initProductGallery);
  else initProductGallery();
})();
