# Hand-authored enrichment for products 16-49 (verified from live store copy).

B = {
"u2AWe": {
  "name": "Professional Hair & Hairstyle Stamp Kit for Procreate",
  "category": "Hair",
  "assets": "160 hair stamps",
  "short": "160 precision hair and hairstyle stamps that solve volume and flow — a solid hair foundation before you start detailing.",
  "features": [
    "160 professional hair stamps for instant volume, flow and hairstyles",
    "Ends the hours-long hair sketching phase",
    "Precision-engineered foundations for strands and detailing",
    "Works for portraits, fashion illustration and character art",
  ],
  "perfectFor": ["Portrait artists", "Fashion illustrators", "Character artists"],
  "tags": ["hair", "hairstyle", "stamps", "strands", "volume", "portrait"],
  "related": ["professional-hair-brushes", "premium-hair-brushes-10", "portrait-mastery-kit-46-brushes", "ultimate-portrait-mastery-bundle"],
  "seoTitle": "Professional Hair & Hairstyle Stamp Kit — 160 Procreate Stamps | DigiKitPro",
  "seoDesc": "160 Procreate hair stamps for instant volume, flow and hairstyles. The pro foundation for portrait hair on iPad. Instant download — $5.00.",
  "featured": 0
},
"Tfm0t": {
  "name": "10 Premium Procreate Brushes Set — Texture & Effects",
  "category": "Glitter & Effects",
  "assets": "10 brushes",
  "short": "Ten carefully crafted texture and effects brushes that add a professional finish to any Procreate artwork.",
  "features": ["10 high-quality, carefully crafted brushes", "Texture & effects for depth and finish", "Each brush built for a unique, useful effect"],
  "perfectFor": ["Digital artists", "Designers", "Illustrators"],
  "tags": ["texture", "effects", "premium", "small set"],
  "related": ["glitter-brushes-sparkle-shine-30", "smoke-brushes-12", "illustration-brushes-2", "tie-dye-brushes-studio"],
  "seoTitle": "10 Premium Procreate Brushes — Texture & Effects Set | DigiKitPro",
  "seoDesc": "10 premium texture & effects brushes for Procreate on iPad. Carefully crafted for professional finishes. Instant download — $5.00.",
  "featured": 0
},
"ZKsJI": {
  "name": "10 Premium Hair Brushes for Procreate",
  "category": "Hair",
  "assets": "10 brushes",
  "short": "Ten realistic hair-texture brushes covering different hair types — flowing strands, texture and volume for digital portraits.",
  "features": ["10 hair-specific premium brushes", "Variety for different hair types and textures", "Realistic, flowing hair effects in portrait work"],
  "perfectFor": ["Portrait artists", "Character artists"],
  "tags": ["hair", "strands", "realistic hair", "portrait"],
  "related": ["professional-hair-brushes", "hair-hairstyle-stamp-kit", "portrait-skin-brushes-procreate", "portrait-mastery-kit-46-brushes"],
  "seoTitle": "10 Premium Hair Brushes for Procreate — Realistic Hair Set | DigiKitPro",
  "seoDesc": "10 realistic hair brushes for Procreate: flowing strands, texture & volume for portraits on iPad. Instant .brushset download — $5.00.",
  "featured": 0
},
"G2N8m": {
  "name": "The DigiKitPro Master Library — 2,000+ Procreate Brushes",
  "category": "Bundles",
  "badge": "Complete Library",
  "assets": "2,000+ organized brushes",
  "short": "The definitive DigiKitPro collection: 2,000+ professional brushes, organized and optimized — every style, one library, no more tool fatigue.",
  "features": [
    "2,000+ professional brushes organized for a pro workflow",
    "Every style covered — portrait, anime, watercolor, traditional, effects and more",
    "Stops 'tool fatigue': the right brushes, curated and searchable",
    "Delivered in 3 ZIP downloads (109MB + 181MB + 162MB)",
  ],
  "perfectFor": ["Professional artists", "Studios", "Artists building a permanent toolkit"],
  "tags": ["master library", "2000", "all brushes", "complete", "mega bundle", "collection"],
  "related": ["master-vault-1000-brushes", "procreate-mega-bundle-650", "ultimate-portrait-mastery-bundle", "artista-studio-kit-76-brushes"],
  "seoTitle": "DigiKitPro Master Library — 2,000+ Procreate Brushes | DigiKitPro",
  "seoDesc": "The complete 2,000+ brush DigiKitPro Master Library for Procreate: every style organized into one pro toolkit. Instant download — $19.00.",
  "featured": 0
},
"gkewa": {
  "name": "Tattoo Artist's Studio Kit — 200+ Procreate Brushes",
  "category": "Other",
  "assets": "200+ brushes",
  "short": "200+ brushes with real needle weight, dotwork grit and stipple texture — pro flash and tattoo concepts designed on iPad.",
  "features": [
    "200+ brushes built for tattoo flash and concept design",
    "Authentic needle weight, dotwork and stippling behavior",
    "Lines with the organic grit of a real tattoo shop",
    "Designs that translate cleanly to skin",
  ],
  "perfectFor": ["Tattoo artists", "Flash designers", "Illustrators"],
  "tags": ["tattoo", "flash", "dotwork", "stipple", "ink", "linework"],
  "related": ["koi-fish-tattoo-brushes", "master-line-art-vault-300", "essential-line-art-sketch-kit", "liner-marker-studio-39-brushes"],
  "seoTitle": "Tattoo Artist's Studio Kit — 200+ Procreate Brushes | DigiKitPro",
  "seoDesc": "200+ tattoo brushes for Procreate: needle-weight lines, dotwork & stipple for pro flash design on iPad. Instant download — $10.00.",
  "featured": 0
},
"8lF29": {
  "name": "Procreate Brush & Color Palette Bundle — 160 Brushes + 12 Palettes",
  "category": "Bundles",
  "assets": "160 brushes + 12 color palettes",
  "short": "160 beautifully crafted pattern brushes paired with 12 expertly curated color palettes — an instant creative toolkit for iPad.",
  "features": ["160 pattern brushes for instant surface detail", "12 curated palettes remove color guesswork", "Professional results for illustration, stickers and social graphics"],
  "perfectFor": ["Illustrators", "Sticker designers", "Surface pattern designers"],
  "tags": ["pattern brushes", "color palettes", "swatches", "bundle", "stickers"],
  "related": ["procreate-palettes-bundle-50", "free-color-vault-1200-swatches", "illustration-brushes-2", "premium-texture-effects-10-brushes"],
  "seoTitle": "160 Procreate Pattern Brushes + 12 Color Palettes Bundle | DigiKitPro",
  "seoDesc": "160 pattern brushes & 12 curated color palettes for Procreate on iPad — instant creative toolkit for illustrators & designers — $5.00.",
  "featured": 0
},
"KM1a5": {
  "name": "Koi Fish Tattoo Procreate Brushes",
  "category": "Other",
  "assets": "Koi tattoo brushset",
  "short": "Bold, clean, highly detailed koi fish tattoo brushes — professional koi artwork drawn directly on your iPad.",
  "features": ["Professional koi tattoo brushset", "Bold, clean, highly detailed designs", "Optimized for seamless Procreate workflow", "Instant .brushset download"],
  "perfectFor": ["Tattoo artists", "Illustrators", "Digital creators"],
  "tags": ["koi", "fish", "tattoo", "japanese", "ink"],
  "related": ["tattoo-artist-studio-kit-200", "japanese-watercolour-collection", "master-line-art-vault-300", "animal-fur-brushes-2"],
  "seoTitle": "Koi Fish Tattoo Procreate Brushes — Koi Brushset for iPad | DigiKitPro",
  "seoDesc": "Professional koi fish tattoo brushes for Procreate: bold, clean, detailed koi artwork on iPad. Instant .brushset download — $9.00.",
  "featured": 0
},
"JfqCA": {
  "name": "Animal Fur 2 — 35 Fur, Hair & Feather Brushes",
  "category": "Other",
  "assets": "35 brushes",
  "short": "35 dynamic fur, hair and feather brushes for realistic animal and fantasy art — soft one stroke, wild the next.",
  "features": ["35 dynamic fur, hair & feather brushes", "Realism with control — texture in intentional strokes", "Built for realistic animal & fantasy artwork"],
  "perfectFor": ["Animal artists", "Fantasy illustrators", "Wildlife artists"],
  "tags": ["fur", "animal", "feather", "wildlife", "fantasy", "texture"],
  "related": ["professional-hair-brushes", "premium-hair-brushes-10", "illustration-brushes-2", "koi-fish-tattoo-brushes"],
  "seoTitle": "Animal Fur 2 — 35 Fur, Hair & Feather Procreate Brushes | DigiKitPro",
  "seoDesc": "35 dynamic fur, hair & feather brushes for Procreate: realistic animal and fantasy art on iPad. Instant download — $5.00.",
  "featured": 0
},
"qOaFE": {
  "name": "Illustration Brushes 2 for Procreate",
  "category": "Other",
  "assets": "15 texture brushes + 5 color palettes",
  "short": "15 authentic textured illustration brushes plus 5 color palettes — made for children's book illustration and hand lettering.",
  "features": ["15 authentic texture brushes", "5 bonus Procreate color palettes", "Pressure-sensitive brushes suited to hand lettering", "Children's book illustration ready"],
  "perfectFor": ["Children's book illustrators", "Lettering artists", "Illustrators"],
  "tags": ["illustration", "texture", "children's book", "lettering", "palettes"],
  "related": ["brush-palette-bundle-160", "procreate-palettes-bundle-50", "premium-texture-effects-10-brushes", "dreamy-pastel-art-kit"],
  "seoTitle": "Illustration Brushes 2 — 15 Texture Brushes + 5 Palettes | DigiKitPro",
  "seoDesc": "15 authentic texture brushes + 5 color palettes for Procreate: children's book illustration & lettering. Instant download — $5.00.",
  "featured": 0
},
"Dqr26": {
  "name": "Professional Hair Brushes for Procreate",
  "category": "Hair",
  "assets": "Hair brush kit",
  "short": "A streamlined hair system that paints believable strands, texture and volume without hours of hand-drawn strokes.",
  "features": ["Streamlined system for believable hair", "Handles texture and volume heavy-lifting", "Natural, flowing results without strand-by-strand painting", "Fine hair textures included"],
  "perfectFor": ["Portrait artists", "Character artists", "Illustrators"],
  "tags": ["hair", "strands", "volume", "portrait", "realistic hair"],
  "related": ["hair-hairstyle-stamp-kit", "premium-hair-brushes-10", "portrait-skin-brushes-procreate", "portrait-mastery-kit-46-brushes"],
  "seoTitle": "Professional Hair Brushes for Procreate — Realistic Hair Kit | DigiKitPro",
  "seoDesc": "Procreate hair brushes that paint believable strands, texture and volume fast — the pro hair system for iPad portraits — $5.00.",
  "featured": 0
},
"PKVXa": {
  "name": "80 Organic Brushes — Watercolor Studio Kit for Procreate",
  "category": "Watercolor",
  "assets": "80 organic brushes",
  "short": "80 organic watercolor brushes engineered for real bleed, pigment flow and grain — digital watercolor with genuine soul.",
  "features": ["80 organic watercolor brushes", "Authentic bleed, flow and paper grain", "Ends 'too clean, too digital' watercolor", "For artists who want traditional feel on iPad"],
  "perfectFor": ["Watercolor artists", "Illustrators", "Traditional media lovers"],
  "tags": ["watercolor", "organic", "washes", "bleed", "grain", "traditional"],
  "related": ["watercolor-studio-kit-50-brushes", "japanese-watercolour-collection", "dreamy-pastel-art-kit", "pro-sketch-traditional-art-kit"],
  "seoTitle": "80 Organic Watercolor Brushes for Procreate | DigiKitPro",
  "seoDesc": "80 organic watercolor brushes for Procreate with real bleed, pigment flow & paper grain. Instant iPad download — $5.00.",
  "featured": 0
},
"mR3Au": {
  "name": "100+ Anime Soft Style Brushes — Watercolor, Shading & Line Art",
  "category": "Anime",
  "assets": "100+ brushes",
  "short": "100+ soft watercolor brushes, smooth blenders and expressive liners for dreamy anime, manga and soft-style illustration.",
  "features": ["100+ brushes: watercolor, soft shading, blending & line art", "Authentic soft-anime watercolor beauty", "Everything for anime, manga and soft illustration in one set"],
  "perfectFor": ["Anime artists", "Manga creators", "Soft-style illustrators"],
  "tags": ["anime", "manga", "soft style", "watercolor", "blending", "line art"],
  "related": ["anime-soft-style-studio-kit", "essential-line-art-sketch-kit", "dreamy-pastel-art-kit", "glitter-brushes-sparkle-shine-30"],
  "seoTitle": "100+ Anime Soft Style Brushes for Procreate | DigiKitPro",
  "seoDesc": "100+ anime soft-style brushes for Procreate: watercolor, blending & expressive line art for dreamy manga illustration — $5.00.",
  "featured": 0
},
"zGwKS": {
  "name": "Free Fine Liner Set — 100 Brushes + 13 Paper Textures",
  "category": "Line Art",
  "badge": "Free",
  "assets": "100 brushes + 13 seamless paper textures",
  "short": "Real pen precision at zero cost: 100 fine liner, micron and marker brushes plus 13 seamless paper textures. Free instant download.",
  "features": ["100 professional fine liner brushes — completely free", "13 seamless paper textures for analog warmth", "Fineliners, micron pens and markers in one set", "Crisp, natural lines with authentic analog texture"],
  "perfectFor": ["Sketchers", "Inkers", "Illustrators", "Lettering artists"],
  "tags": ["free", "fine liner", "liner", "pen", "micron", "paper textures", "inking"],
  "related": ["essential-line-art-sketch-kit", "master-line-art-vault-300", "liner-marker-studio-39-brushes", "free-chalkboard-artists-toolkit"],
  "seoTitle": "Free Fine Liner Brushes for Procreate — 100 Brushes + 13 Papers | DigiKitPro",
  "seoDesc": "Free Procreate download: 100 fine liner, micron & marker brushes plus 13 seamless paper textures. Real pen precision on iPad — $0.",
  "featured": 10,
  "free": True
},
"TIWNx": {
  "name": "Professional Sketchbook Procreate Brushes — Traditional Media & Drawing Kit",
  "category": "Sketching",
  "assets": "Traditional media drawing kit",
  "short": "Gritty textures, organic linework and effortless blending — a sketchbook studio that turns your iPad into a high-end paper canvas.",
  "features": ["Meticulously crafted traditional-media brushes", "Gritty textures and organic linework", "From blocking shapes to fine-tooth detail", "Effortless physical-media style blending"],
  "perfectFor": ["Sketchbook artists", "Traditional media lovers", "Concept artists"],
  "tags": ["sketchbook", "traditional", "drawing", "pencil", "ink", "paper"],
  "related": ["professional-digital-sketchbook", "pro-sketch-traditional-art-kit", "professional-charcoal-studio", "essential-line-art-sketch-kit"],
  "seoTitle": "Professional Sketchbook Brushes — Traditional Media Kit | DigiKitPro",
  "seoDesc": "Traditional media & drawing kit for Procreate: gritty textures, organic linework and blending that feel like a real sketchbook — $10.00.",
  "featured": 0
},
"CK2LX": {
  "name": "Procreate Palettes Bundle — 50 Sets × 30 Swatches",
  "category": "Other",
  "assets": "50 palettes / 1,500 swatches",
  "short": "50 ready-to-use palettes of 30 hand-picked swatches each — jump straight into creating without second-guessing color.",
  "features": ["50 palettes × 30 curated swatches", "Keep artwork cohesive and polished", "Explore styles and moods instantly", "For painting, illustration, stickers and social graphics"],
  "perfectFor": ["Illustrators", "Painters", "Sticker designers", "Color explorers"],
  "tags": ["color palettes", "swatches", "color", "palettes bundle"],
  "related": ["free-color-vault-1200-swatches", "brush-palette-bundle-160", "illustration-brushes-2", "artista-studio-kit-76-brushes"],
  "seoTitle": "Procreate Palettes Bundle — 50 Sets, 30 Swatches Each | DigiKitPro",
  "seoDesc": "50 Procreate color palettes of 30 curated swatches each — 1,500 colors, cohesive artwork instantly. Instant download — $5.00.",
  "featured": 0
},
"VtnCF": {
  "name": "Master Vault Mega Bundle — 1,000+ Procreate Brushes",
  "category": "Bundles",
  "badge": "Mega Bundle",
  "assets": "1,000+ brushes",
  "short": "1,000+ professional brushes ending the endless scroll — realistic skin, anime line-art and traditional textures in one vault.",
  "features": ["1,000+ professional, curated brushes", "Skin, anime, traditional and effect brushes in one vault", "Ends random-brush scrolling for good", "3 ZIP downloads (197MB + 183MB + 199MB)"],
  "perfectFor": ["Working artists", "Illustrators", "Studios"],
  "tags": ["mega bundle", "1000", "vault", "complete collection"],
  "related": ["master-library-2000-brushes", "procreate-mega-bundle-650", "ultimate-portrait-mastery-bundle", "artista-studio-kit-76-brushes"],
  "seoTitle": "Master Vault Mega Bundle — 1,000+ Procreate Brushes | DigiKitPro",
  "seoDesc": "1,000+ curated Procreate brushes in one Master Vault: skin, anime line-art, traditional textures & more. Instant download — $15.00.",
  "featured": 0
},
"Rexg7": {
  "name": "Chalkboard Artist's Toolkit — 20+ Chalk Brushes (Free)",
  "category": "Traditional",
  "badge": "Free",
  "assets": "20+ chalk brushes",
  "short": "The raw essence of traditional chalk on your iPad: 20+ dusty, tactile chalk brushes with real blackboard soul. Free download.",
  "features": ["20+ professional chalk brushes — free", "Organic, dusty, tactile blackboard feel", "Captured essence of traditional chalk", "For lettering, menus, signage and illustration"],
  "perfectFor": ["Lettering artists", "Signage & menu designers", "Illustrators"],
  "tags": ["free", "chalk", "chalkboard", "dusty", "lettering", "traditional"],
  "related": ["professional-charcoal-studio", "dreamy-pastel-art-kit", "pro-sketch-traditional-art-kit", "free-fine-liner-brushes-100"],
  "seoTitle": "Free Chalkboard Artist's Toolkit — 20+ Chalk Brushes | DigiKitPro",
  "seoDesc": "Free Procreate chalk brushes: 20+ professional tools with real blackboard dust and texture for lettering & illustration — $0.",
  "featured": 11,
  "free": True
},
"UQ6pN": {
  "name": "Master Line-Art Vault — 300+ Fine Line Brushes",
  "category": "Line Art",
  "assets": "300+ brushes",
  "short": "The ultimate all-in-one linework collection: 300+ fine line brushes with the precision, variety and character pro artwork demands.",
  "features": ["300+ fine line brushes for every linework need", "Precision plus authentic character", "From clean technical lines to textured organic strokes", "The one linework library to rule your workflow"],
  "perfectFor": ["Line artists", "Inkers", "Tattoo designers", "Illustrators"],
  "tags": ["line art", "fine line", "liner", "inking", "vault", "300"],
  "related": ["essential-line-art-sketch-kit", "free-fine-liner-brushes-100", "liner-marker-studio-39-brushes", "tattoo-artist-studio-kit-200"],
  "seoTitle": "Master Line-Art Vault — 300+ Fine Line Procreate Brushes | DigiKitPro",
  "seoDesc": "300+ fine line brushes for Procreate: the all-in-one linework vault with precision, variety and authentic texture — $5.00.",
  "featured": 0
},
"BmFdZ": {
  "name": "Ultimate Procreate Color Vault — 1,200+ Swatches (Free)",
  "category": "Other",
  "badge": "Free",
  "assets": "40 palettes / 1,200+ swatches",
  "short": "40 professional palettes — 1,200+ curated swatches — so you never burn the first hour of a painting hunting for the right shade.",
  "features": ["1,200+ curated pro swatches — free", "40 ready-to-use palettes", "Cohesive color without the guesswork", "Instant Procreate palette import"],
  "perfectFor": ["Painters", "Illustrators", "Every iPad artist"],
  "tags": ["free", "color", "palettes", "swatches", "color vault"],
  "related": ["procreate-palettes-bundle-50", "brush-palette-bundle-160", "free-fine-liner-brushes-100", "free-chalkboard-artists-toolkit"],
  "seoTitle": "Free Procreate Color Vault — 1,200+ Swatches | DigiKitPro",
  "seoDesc": "Free Procreate color library: 40 palettes, 1,200+ professional swatches for instant cohesive color on iPad — $0.",
  "featured": 12,
  "free": True
},
"LmOr8": {
  "name": "10-Minute Daily Mindfulness System — 57-Page Planner",
  "category": "Other",
  "assets": "57 pages, hyperlinked PDF + Canva template",
  "short": "A 57-page mindfulness planner with 10-minute daily prompts, fully hyperlinked PDF plus an editable Canva template.",
  "features": ["57 beautifully designed pages", "10-minute daily prompts for busy lives", "Fully hyperlinked for fast navigation", "Editable Canva template included"],
  "perfectFor": ["Busy professionals", "Mindfulness beginners", "Anxious minds"],
  "tags": ["planner", "mindfulness", "wellness", "journal", "pdf", "canva"],
  "related": ["wellness-journal-2026", "wellness-journal-365", "adhd-planner-2026", "undated-planner-dark-mode"],
  "seoTitle": "10-Minute Daily Mindfulness System — 57 Pages | DigiKitPro",
  "seoDesc": "57-page digital mindfulness planner: 10-minute daily prompts, hyperlinked PDF + editable Canva template. Instant download — $5.00.",
  "featured": 0
},
"bUHGy": {
  "name": "2026 Digital Wellness Journal",
  "category": "Other",
  "assets": "Dated daily wellness planner",
  "short": "A dated 2026 daily wellness journal for self-care, fitness and reflection — stay consistent with guided tracking all year.",
  "features": ["Dated daily wellness pages for 2026", "Guided spaces for habit & wellness tracking", "Self-care routines and reflection prompts", "Mind, body and soul focus"],
  "perfectFor": ["Wellness enthusiasts", "Habit builders", "Reflective journalers"],
  "tags": ["journal", "wellness", "2026", "planner", "self-care", "fitness"],
  "related": ["mindfulness-system-planner", "wellness-journal-365", "wellness-fitness-planner-goodnotes", "adhd-planner-2026"],
  "seoTitle": "2026 Digital Wellness Journal — Daily Self-Care Planner | DigiKitPro",
  "seoDesc": "Dated 2026 digital wellness journal: daily self-care, fitness & reflection pages to stay consistent all year — $5.00.",
  "featured": 0
},
"Q2UdG": {
  "name": "Digital Wellness & Fitness Planner for GoodNotes",
  "category": "Other",
  "assets": "GoodNotes wellness & fitness planner",
  "short": "A structured digital wellness and fitness map for GoodNotes — workouts, nutrition and goals aligned in one plan.",
  "features": ["Structured fitness & wellness planning", "Workout and nutrition alignment", "Built for GoodNotes workflow", "Goal mapping for sustainable progress"],
  "perfectFor": ["Fitness beginners", "GoodNotes users", "Wellness planners"],
  "tags": ["fitness", "wellness", "goodnotes", "planner", "workout", "nutrition"],
  "related": ["ultimate-fitness-planner", "wellness-journal-2026", "mindfulness-system-planner", "undated-planner-dark-mode"],
  "seoTitle": "Digital Wellness & Fitness Planner for GoodNotes | DigiKitPro",
  "seoDesc": "Digital wellness & fitness planner for GoodNotes: structured workouts, nutrition and goal planning on your device — $5.00.",
  "featured": 0
},
"0RGu9": {
  "name": "Digital 2026 ADHD Balanced Mind Planner & Wellness Journal",
  "category": "Other",
  "assets": "55 pages",
  "short": "A 55-page ADHD-friendly planner for 2026: reduce mental noise, regulate emotions and build gentle routines without overwhelm.",
  "features": ["Designed for ADHD & neurodivergent minds", "55 pages of balance-focused tools", "Emotional regulation and energy management", "Gentle routines without pressure"],
  "perfectFor": ["ADHD minds", "Neurodivergent adults", "Gentle routine builders"],
  "tags": ["adhd", "planner", "wellness", "neurodivergent", "2026", "journal"],
  "related": ["mindfulness-system-planner", "wellness-journal-2026", "wellness-journal-365", "undated-planner-dark-mode"],
  "seoTitle": "2026 ADHD Balanced Mind Planner — 55 Pages | DigiKitPro",
  "seoDesc": "55-page digital ADHD planner & wellness journal for 2026: gentle routines, emotional regulation and focus tools — $7.00.",
  "featured": 0
},
"oKdcU": {
  "name": "Japanese Watercolour Collection — 43 Illustrations + Patterns",
  "category": "Other",
  "assets": "43 illustrations + seamless patterns + posters",
  "short": "Premium Japanese-inspired watercolour illustrations, seamless patterns, posters and bonus elements for branding and print.",
  "features": ["43 detailed oriental-aesthetic illustrations", "Seamless patterns and posters included", "Bonus design elements", "For branding, stationery, POD and wall art"],
  "perfectFor": ["Designers", "Print-on-demand sellers", "Stationery brands"],
  "tags": ["japanese", "watercolour", "illustrations", "patterns", "posters", "oriental", "design assets"],
  "related": ["koi-fish-tattoo-brushes", "watercolor-studio-kit-50-brushes", "organic-watercolor-80-brushes", "christmas-brushes-bundle"],
  "seoTitle": "Japanese Watercolour Collection — 43 Illustrations & Patterns | DigiKitPro",
  "seoDesc": "43 Japanese-inspired watercolour illustrations, seamless patterns & posters for branding, stationery and print-on-demand — $9.00.",
  "featured": 0
},
"PwLIh": {
  "name": "Digital Wellness Journal — 365 Hyperlinked Pages, Dark Mode",
  "category": "Other",
  "assets": "365 pages, minimalist dark mode",
  "short": "365 undated daily wellness pages in a distraction-free dark minimalist design for GoodNotes and Notability.",
  "features": ["365 undated daily wellness pages", "Coal-black minimalist dark mode design", "Fully hyperlinked navigation", "For GoodNotes & Notability"],
  "perfectFor": ["Daily journalers", "Minimalists", "Dark mode lovers"],
  "tags": ["wellness", "journal", "365", "dark mode", "goodnotes", "notability", "minimalist"],
  "related": ["undated-planner-dark-mode", "mindfulness-system-planner", "wellness-journal-2026", "adhd-planner-2026"],
  "seoTitle": "Digital Wellness Journal — 365 Pages, Dark Mode | DigiKitPro",
  "seoDesc": "365-page dark mode digital wellness journal: undated, hyperlinked minimalist planner for GoodNotes & Notability — $5.00.",
  "featured": 0
},
"Yelrz": {
  "name": "Pro-Sketch Traditional Art Kit for Procreate",
  "category": "Traditional",
  "assets": "Traditional media kit",
  "short": "Wax crayon grain, oil pastel blends and real sketchbook grit — physical media's raw soul delivered to your iPad.",
  "features": ["Raw, organic physical-media feel", "From wax crayon grain to smooth oil pastel blends", "Kills the 'too digital, too plastic' look", "Hand-drawn warmth with digital flexibility"],
  "perfectFor": ["Traditional media artists", "Sketchbook lovers", "Illustrators"],
  "tags": ["traditional", "crayon", "oil pastel", "sketch", "organic", "texture"],
  "related": ["professional-charcoal-studio", "dreamy-pastel-art-kit", "sketchbook-traditional-media-kit", "professional-digital-sketchbook"],
  "seoTitle": "Pro-Sketch Traditional Art Kit for Procreate | DigiKitPro",
  "seoDesc": "Traditional media Procreate kit: wax crayon grain, oil pastel blends and authentic sketchbook texture for organic digital art — $5.00.",
  "featured": 0
},
"MTAev": {
  "name": "Smoke Procreate Brushes — 12 Realistic Smoke Effects",
  "category": "Glitter & Effects",
  "assets": "12 brushes",
  "short": "Twelve realistic smoke brushes for cinematic overlays, atmospheric depth and dramatic impact in seconds.",
  "features": ["12 realistic smoke effect brushes", "Cinematic overlays in seconds", "Atmospheric depth and drama", "For illustrators and photo editors"],
  "perfectFor": ["Digital artists", "Illustrators", "Photo editors"],
  "tags": ["smoke", "effects", "cinematic", "atmosphere", "overlay"],
  "related": ["glitter-brushes-sparkle-shine-30", "premium-texture-effects-10-brushes", "tie-dye-brushes-studio", "anime-soft-style-studio-kit"],
  "seoTitle": "Smoke Procreate Brushes — 12 Realistic Smoke Effects | DigiKitPro",
  "seoDesc": "12 realistic smoke brushes for Procreate: cinematic overlays and atmospheric depth on iPad in seconds. Instant download — $4.00.",
  "featured": 0
},
"jFL0I": {
  "name": "100+ Editable KDP Templates 2026 — Canva Bundle",
  "category": "Other",
  "assets": "100+ Canva templates",
  "short": "100+ fully editable Canva planner, journal, logbook and workbook templates ready for Amazon KDP publishing in 2026.",
  "features": ["100+ editable Canva templates", "Planners, journals, logbooks & workbooks", "Beginner friendly drag-and-drop editing", "KDP-upload ready for 2026"],
  "perfectFor": ["KDP publishers", "Side hustlers", "Template sellers"],
  "tags": ["kdp", "canva", "templates", "planner", "journal", "publishing"],
  "related": ["mindfulness-system-planner", "ultimate-fitness-planner", "wellness-journal-365", "brush-palette-bundle-160"],
  "seoTitle": "100+ Editable KDP Templates 2026 — Canva Bundle | DigiKitPro",
  "seoDesc": "100+ editable Canva templates for Amazon KDP: planners, journals, logbooks & workbooks, ready to customize and publish — $8.00.",
  "featured": 0
},
"XqrPB": {
  "name": "Tie Dye Brushes Studio for Procreate",
  "category": "Glitter & Effects",
  "assets": "21 brushes & stamps",
  "short": "21 meticulously crafted tie-dye brushes and stamps that turn your canvas into a vibrant tapestry of color.",
  "features": ["21 tie-dye brushes and stamps", "Vibrant spirals, bleeds and fabric textures", "Authentic tie-dye essence digitally"],
  "perfectFor": ["Illustrators", "Pattern designers", "Apparel mockups"],
  "tags": ["tie dye", "tie-dye", "colorful", "stamps", "fabric", "effects"],
  "related": ["glitter-brushes-sparkle-shine-30", "premium-texture-effects-10-brushes", "smoke-brushes-12", "christmas-brushes-bundle"],
  "seoTitle": "Tie Dye Brushes Studio for Procreate — 21 Brushes | DigiKitPro",
  "seoDesc": "21 tie-dye brushes & stamps for Procreate: vibrant spirals and fabric textures for colorful iPad artwork. Instant download — $7.00.",
  "featured": 0
},
"UEyGg": {
  "name": "Christmas Procreate Brushes Bundle",
  "category": "Bundles",
  "assets": "173 stamps & brushes + 44 washi tapes + more",
  "short": "A festive mega-pack: 173 Christmas stamps and brushes plus 44 hand-drawn washi tapes and seasonal extras for holiday artwork.",
  "features": ["173 Christmas decor stamps & brushes", "44 hand-drawn washi tapes", "Cookie-cutter shapes, embellishments & florals", "Everything for holiday cards and seasonal design"],
  "perfectFor": ["Holiday card designers", "Seasonal illustrators", "Crafters"],
  "tags": ["christmas", "holiday", "stamps", "washi tape", "festive", "bundle"],
  "related": ["glitter-brushes-sparkle-shine-30", "tie-dye-brushes-studio", "brush-palette-bundle-160", "halloween-pumpkin-bundle"],
  "seoTitle": "Christmas Procreate Brushes Bundle — 217+ Festive Assets | DigiKitPro",
  "seoDesc": "Christmas Procreate bundle: 173 stamps & brushes, 44 washi tapes and festive extras for stunning holiday artwork on iPad — $8.00.",
  "featured": 0
},
"sv2ud": {
  "name": "Undated Digital Planner — Dark Mode",
  "category": "Other",
  "assets": "2 planners + 1,000 stickers",
  "short": "A dark, fully hyperlinked undated planner with Monday and Sunday start versions plus 1,000 stickers.",
  "features": ["2 undated planners: Monday & Sunday start", "Fully hyperlinked for effortless navigation", "1,000 stickers included", "Creative dark design"],
  "perfectFor": ["Planner lovers", "Dark mode fans", "Goal setters"],
  "tags": ["planner", "undated", "dark mode", "stickers", "organization"],
  "related": ["wellness-journal-365", "adhd-planner-2026", "mindfulness-system-planner", "wellness-journal-2026"],
  "seoTitle": "Undated Digital Planner Dark Mode + 1,000 Stickers | DigiKitPro",
  "seoDesc": "Dark undated digital planner: Monday & Sunday start versions, fully hyperlinked, plus 1,000 stickers. Instant download — $7.00.",
  "featured": 0
},
"BG7ob": {
  "name": "Discover Morocco in 7 Days — Marrakech to Sahara Itinerary",
  "category": "Other",
  "assets": "PDF travel guide",
  "short": "A step-by-step 7-day Morocco itinerary from Marrakech through Fes and the Atlas Mountains to the Sahara Desert.",
  "features": ["Complete 7-day itinerary", "Marrakech, Fes, Atlas Mountains & Sahara", "Culture, history and landscape highlights", "Delivered as PDF (30MB) + bonus PDF"],
  "perfectFor": ["Morocco travelers", "One-week trip planners", "Adventurers"],
  "tags": ["morocco", "travel", "itinerary", "marrakech", "sahara", "pdf guide"],
  "related": ["mindfulness-system-planner", "wellness-journal-2026", "undated-planner-dark-mode", "ultimate-fitness-planner"],
  "seoTitle": "Discover Morocco in 7 Days — Ultimate Itinerary PDF | DigiKitPro",
  "seoDesc": "7-day Morocco itinerary PDF: Marrakech, Fes, Atlas Mountains to the Sahara Desert, step by step. Instant download — $5.00.",
  "featured": 0
},
"plxDu": {
  "name": "Ultimate Fitness Planner for Peak Performance",
  "category": "Other",
  "assets": "Digital fitness planner (PDF)",
  "short": "A beautifully designed fitness planner for goal setting, workout schedules, meal planning, habit tracking and self-care.",
  "features": ["Personalized goal setting", "Workout schedules and progress tracking", "Meal planning and habit trackers", "Self-care reminders built in"],
  "perfectFor": ["Women building routines", "Fitness beginners", "Habit trackers"],
  "tags": ["fitness", "planner", "workout", "meal planning", "habits", "pdf"],
  "related": ["wellness-fitness-planner-goodnotes", "wellness-journal-2026", "mindfulness-system-planner", "undated-planner-dark-mode"],
  "seoTitle": "Ultimate Fitness Planner — Peak Performance PDF | DigiKitPro",
  "seoDesc": "Digital fitness planner: goals, workouts, meal planning, habit trackers & self-care in one beautiful PDF. Instant download — $10.00.",
  "featured": 0
},
"SWUCM": {
  "name": "Halloween Spooky Pumpkin Bundle — 20 PNGs",
  "category": "Other",
  "assets": "20 PNGs at 300 DPI",
  "short": "Twenty high-quality 300 DPI pumpkin-themed spooky illustrations in PNG format for seasonal designs.",
  "features": ["20 high-quality PNG files", "300 DPI print-ready resolution", "Spooky and fun pumpkin illustrations", "Instant seasonal design assets"],
  "perfectFor": ["Seasonal designers", "Crafters", "POD sellers"],
  "tags": ["halloween", "pumpkin", "spooky", "png", "seasonal", "300 dpi"],
  "related": ["christmas-brushes-bundle", "tie-dye-brushes-studio", "japanese-watercolour-collection", "kdp-templates-bundle-100"],
  "seoTitle": "Halloween Spooky Pumpkin Bundle — 20 PNGs, 300 DPI | DigiKitPro",
  "seoDesc": "20 spooky pumpkin PNG illustrations at 300 DPI for Halloween designs, crafting and print-on-demand. Instant download — $4.00.",
  "featured": 0
},
}
