# Hand-authored enrichment for the hero catalog (products 1-15).
# Every fact below is derived from the live DigiKitPro Payhip store copy.

A = {
"btOrh": {
  "name": "Portrait Skin Brushes for Procreate",
  "category": "Skin Texture",
  "badge": "Best Seller",
  "assets": "19 professional brushes",
  "short": "19 premium skin-texture brushes: pores, freckles, wrinkles and textured blenders that turn flat paintings into believable portraits.",
  "features": [
    "All-in-one skin painting solution — no more switching between multiple brush packs",
    "Professional-level realism: natural pores, freckles, fine wrinkles and imperfections",
    "Textured blending brushes that avoid the plastic, over-airbrushed look",
    "Optimized for illustrators, character designers and portrait painters",
    "Beginner friendly, with enough depth for professional commissions",
  ],
  "included": [
    "Realistic skin texture brushes",
    "Freckles brush",
    "Blemishes and pores brushes",
    "Wrinkles and crinkles brushes",
    "Eyelashes detail brush",
    "Textured blending brushes (avoids overly smooth blending)",
    "Sketch pencil for portrait foundations",
    "Base layer painting brush for smooth skin build-up",
    "Blusher brush",
    "Highlighter brush",
    "Juicy zit detail brush for ultra-realistic character work",
    "Bonus scaly texture brush for fantasy, alien or reptile skin",
  ],
  "perfectFor": ["Portrait artists", "Character designers", "Digital painters", "Illustrators"],
  "tags": ["skin", "skin texture", "pores", "freckles", "wrinkles", "portrait", "realistic", "blending", "blusher", "highlighter"],
  "related": ["portrait-mastery-kit-46-brushes", "ultimate-portrait-mastery-bundle", "artista-studio-kit-76-brushes", "professional-hair-brushes"],
  "seoTitle": "Portrait Skin Brushes for Procreate — 19 Realistic Skin Brushes | DigiKitPro",
  "seoDesc": "19 professional Procreate skin brushes for realistic pores, freckles, wrinkles and textured blending. Instant .brushset download for iPad — $5.00.",
  "featured": 1
},
"IjRTk": {
  "name": "Artista Studio Kit — 76 Procreate Brushes",
  "category": "Portrait",
  "assets": "76 versatile brushes",
  "short": "One organized 76-brush collection that covers the full studio workflow — linework, inking, sketching, shading, graphite, markers and effects.",
  "features": [
    "Complete all-in-one workflow: one kit from first sketch to final effect",
    "Eight curated sections keep 76 brushes organized and fast to navigate",
    "Covers linework, shading, graphite, charcoal, markers and traditional media",
    "Built for comics, concept art, portraits, illustration and character design",
  ],
  "included": ["Linework & Inking brushes", "Sketching brushes", "Shading brushes", "Graphite & Charcoal brushes", "Markers", "Traditional Media brushes", "Texture & Effects brushes", "Experimental brushes"],
  "perfectFor": ["Comics", "Concept art", "Portraits", "Illustration", "Character design", "Sketching"],
  "tags": ["studio kit", "all in one", "inking", "shading", "graphite", "charcoal", "markers", "illustration", "comics"],
  "related": ["portrait-mastery-kit-46-brushes", "portrait-skin-brushes-procreate", "essential-line-art-sketch-kit", "procreate-mega-bundle-650"],
  "seoTitle": "Artista Studio Kit — 76 Procreate Brushes for iPad Artists | DigiKitPro",
  "seoDesc": "76 pro Procreate brushes in one organized studio kit: linework, sketching, shading, graphite, markers, textures & effects. Instant download — $5.00.",
  "featured": 4
},
"pOG6v": {
  "name": "Portrait Mastery Kit — 46 Procreate Brushes",
  "category": "Portrait",
  "badge": "Best Seller",
  "assets": "46 brushes + 4 paper textures",
  "short": "A portrait-specific workflow kit: 46 pro brushes plus 4 paper textures organized into sketch, ink, blend, hair, detail, texture and finish.",
  "features": [
    "Covers the entire portrait workflow — first sketch to final polish",
    "Seven workflow-organized sections plus 4 high-quality paper textures",
    "Apple Pencil pressure & tilt support, Procreate 5+",
    "Hand-tested for natural texture buildup on real portrait work",
  ],
  "included": [
    "SKETCH — 8 brushes: pencils, liners and foundation tools",
    "INK — 6 brushes: clean lines, expressive strokes and markers",
    "BLEND — 6 brushes: smooth blending and soft transitions",
    "HAIR — 7 brushes: natural hair, strands and directional details",
    "DETAIL — 6 brushes: fine facial details and sharp finishing touches",
    "TEXTURE — 9 brushes: grain, grit and surface textures",
    "FINISH — 4 brushes: highlights, glow and final polish",
    "PAPER — 4 high-quality textures for a traditional feel",
  ],
  "perfectFor": ["Portraits", "Character art", "Illustration", "Concept art", "Digital sketching", "Realistic artwork"],
  "tags": ["portrait", "portrait workflow", "skin", "hair", "blending", "paper texture", "face", "realistic"],
  "related": ["portrait-skin-brushes-procreate", "ultimate-portrait-mastery-bundle", "hair-hairstyle-stamp-kit", "professional-hair-brushes"],
  "seoTitle": "Portrait Mastery Kit — 46 Procreate Brushes + 4 Paper Textures | DigiKitPro",
  "seoDesc": "Complete 46-brush Procreate portrait kit with 4 paper textures: sketch, ink, blend, hair, detail, texture & finish. Procreate 5+. Instant download — $8.00.",
  "featured": 2
},
"b70QE": {
  "name": "Essential Line Art & Sketch Kit for Procreate",
  "category": "Line Art",
  "assets": "43 brushes + 1 bonus texture brush",
  "short": "43 focused brushes plus a bonus texture brush for clean line art, natural pencil sketches and confident inking — no pack-switching.",
  "features": [
    "Precise, pressure-sensitive liners built for clean line art",
    "Realistic graphite pencils for natural sketching",
    "Detailing brushes for small, controlled work",
    "Manga, comics, character design and illustration ready",
  ],
  "included": [
    "PENCIL — 14 brushes: realistic graphite textures",
    "LINERS — 12 brushes: clean, crisp, pressure-sensitive",
    "INK — 7 brushes: dynamic expressive strokes",
    "DETAILERS — 6 brushes: fine detail and precision work",
    "SKETCH TOOLS — 3 brushes: rough and soft idea brushes",
    "BONUS TEXTURE — 1 brush for natural paper feel",
  ],
  "perfectFor": ["Manga", "Comics", "Character design", "Illustration", "Concept art", "Line art"],
  "tags": ["line art", "liner", "inking", "pencil", "sketch", "manga", "comics", "graphite"],
  "related": ["liner-marker-studio-39-brushes", "master-line-art-vault-300", "free-fine-liner-brushes-100", "professional-digital-sketchbook"],
  "seoTitle": "Essential Line Art & Sketch Kit — 43 Procreate Brushes | DigiKitPro",
  "seoDesc": "Clean lines and natural sketches: 43 Procreate brushes for pencils, liners, ink & detail, plus a bonus paper-texture brush. Instant download — $5.00.",
  "featured": 6
},
"2h0iG": {
  "name": "Ultimate Portrait Mastery Bundle — 4 Procreate Kits",
  "category": "Bundles",
  "badge": "Best Value",
  "assets": "252+ assets across 4 complete kits",
  "short": "Four professional portrait kits in one workflow: line art (43), skin texture (19), hair stamps (160) and glitter effects (30) — 252+ assets.",
  "features": [
    "Complete workflow: sketch → line art → skin → hair → lighting & effects",
    "252+ professional assets in 4 complete, organized kits",
    "Designed specifically for portrait artists, realistic or stylized",
    "Apple Pencil pressure & tilt support, instant download, lifetime access",
    "Better value than buying the four kits separately",
  ],
  "included": [
    "Essential Line-Art & Sketching Kit — 43 brushes",
    "Professional Skin Texture Kit — 19 brushes",
    "Hair & Hairstyle Stamp Kit — 160 stamps",
    "Glitter & Shine Pro Set — 30 brushes",
    "Procreate .brushset files in 4 ZIP downloads (77MB, 19MB, 67MB, 31MB)",
  ],
  "bundleContents": [
    {"name": "Essential Line-Art & Sketching Kit", "count": "43 brushes"},
    {"name": "Professional Skin Texture Kit", "count": "19 brushes"},
    {"name": "Hair & Hairstyle Stamp Kit", "count": "160 stamps"},
    {"name": "Glitter & Shine Pro Set", "count": "30 brushes"},
  ],
  "perfectFor": ["Portrait artists", "Digital illustrators", "Character artists", "Concept artists", "Beauty & fashion artwork"],
  "tags": ["bundle", "portrait", "skin", "hair", "glitter", "line art", "workflow", "value"],
  "related": ["portrait-skin-brushes-procreate", "portrait-mastery-kit-46-brushes", "hair-hairstyle-stamp-kit", "procreate-mega-bundle-650"],
  "seoTitle": "Ultimate Portrait Mastery Bundle — 4 Procreate Kits, 252+ Assets | DigiKitPro",
  "seoDesc": "4 pro portrait kits in one bundle: 43 line-art + 19 skin + 160 hair stamps + 30 glitter brushes for Procreate. Instant download — $15.00.",
  "featured": 3
},
"yce9b": {
  "name": "Anime Soft-Style Studio Kit — 100+ Procreate Brushes",
  "category": "Anime",
  "assets": "100+ handcrafted brushes",
  "short": "A complete anime ecosystem: 100+ brushes for soft gradients, luminous shading, razor-sharp manga ink and glowing final details.",
  "features": [
    "Complete anime workflow from rough sketch to glowing detail",
    "Linework suite: bold manga ink to delicate chibi liners",
    "Shading & blending tools for seamless anime skin transitions",
    "Soft watercolor-style textures and luminous highlights",
  ],
  "perfectFor": ["Anime", "Manga", "Character design", "Dreamy romantic scenes", "Manga panels"],
  "tags": ["anime", "manga", "soft style", "shading", "blending", "cel", "chibi", "watercolor"],
  "related": ["anime-soft-style-brushes-100", "dreamy-pastel-art-kit", "essential-line-art-sketch-kit", "glitter-brushes-sparkle-shine-30"],
  "seoTitle": "Anime Soft-Style Studio Kit — 100+ Procreate Brushes | DigiKitPro",
  "seoDesc": "100+ Procreate brushes engineered for the soft anime look: manga ink liners, seamless blending, watercolor textures & glowing details — $5.00.",
  "featured": 5
},
"6nNtu": {
  "name": "30 Glitter Procreate Brushes — Sparkle & Shine Set",
  "category": "Glitter & Effects",
  "assets": "30 brushes",
  "short": "Thirty responsive glitter, sparkle and glow brushes — from whisper-soft glimmer to radiant flare for lettering, makeup and highlights.",
  "features": [
    "From gentle twinkle to dramatic flare in a single stroke",
    "Ideal for lettering glow, makeup sparkle, jewelry and highlights",
    "Apple Pencil-responsive textures with no extra steps",
    "Lifts flat illustrations into vivid, light-catching artwork",
  ],
  "perfectFor": ["Lettering artists", "Illustrators", "Content creators", "Designers", "Makeup & beauty art"],
  "tags": ["glitter", "sparkle", "shine", "glow", "highlights", "lettering", "effects"],
  "related": ["smoke-brushes-12", "ultimate-portrait-mastery-bundle", "premium-texture-effects-10-brushes", "tie-dye-brushes-studio"],
  "seoTitle": "30 Glitter Procreate Brushes — Sparkle & Shine Brush Set | DigiKitPro",
  "seoDesc": "30 Procreate glitter brushes for sparkle, glow, jewelry, makeup and lettering highlights. Apple Pencil ready, instant .brushset download — $5.00.",
  "featured": 8
},
"hYlF3": {
  "name": "50+ Realistic Watercolor Studio Kit for Procreate",
  "category": "Watercolor",
  "assets": "50+ brushes incl. 30 pigment core + 5 blenders",
  "short": "A real artist's watercolor palette simulated for iPad: 50+ brushes with organic bleed, pigment flow and authentic paper grain.",
  "features": [
    "Replicates fluid behavior, soft washes and raw texture of real watercolor",
    "30-brush pigment core from fine-detail liners to broad wet washes",
    "5 professional blenders for opacity and flow control",
    "For delicate botanicals, dreamy landscapes and ethereal portraits",
  ],
  "perfectFor": ["Watercolor artists", "Botanical illustration", "Landscapes", "Soft portraits"],
  "tags": ["watercolor", "watercolour", "washes", "bleed", "pigment", "botanical", "traditional"],
  "related": ["organic-watercolor-80-brushes", "dreamy-pastel-art-kit", "professional-charcoal-studio", "pro-sketch-traditional-art-kit"],
  "seoTitle": "50+ Realistic Watercolor Studio Kit for Procreate | DigiKitPro",
  "seoDesc": "50+ Procreate watercolor brushes with real pigment flow, organic bleed & paper grain — 30-brush pigment core plus 5 blenders. Instant download — $10.00.",
  "featured": 7
},
"cxE90": {
  "name": "Professional Digital Sketchbook for Procreate",
  "category": "Sketching",
  "assets": "Brush & texture system with paper textures + torn-paper stamps",
  "short": "A complete tactile sketchbook environment: sketching tools, seamless paper textures and torn-paper stamps that give digital work real soul.",
  "features": [
    "Replicates graphite and ink on raw paper",
    "Seamless paper textures + torn-paper stamps for depth and character",
    "Grip, texture and dimension missing from a sterile digital canvas",
    "For concepts, anatomy studies and spontaneous doodles alike",
  ],
  "perfectFor": ["Concept drafting", "Anatomy studies", "Sketchbook artists", "Doodles & studies"],
  "tags": ["sketchbook", "sketching", "paper texture", "graphite", "ink", "drawing", "studies"],
  "related": ["sketchbook-traditional-media-kit", "essential-line-art-sketch-kit", "pro-sketch-traditional-art-kit", "professional-charcoal-studio"],
  "seoTitle": "Professional Digital Sketchbook for Procreate — Brushes + Textures | DigiKitPro",
  "seoDesc": "A complete sketchbook system for Procreate: sketching brushes, seamless paper textures & torn-paper stamps for authentic traditional feel — $5.00.",
  "featured": 0
},
"QrVkj": {
  "name": "Professional Liner & Marker Studio — 39 High-Fidelity Brushes",
  "category": "Line Art",
  "assets": "39 high-fidelity brushes",
  "short": "A curated digital ink station: 39 brushes replicating the saturated flow of alcohol markers and the razor precision of technical liners.",
  "features": [
    "Marker behavior with organic bleed and wet saturation",
    "Technical-pen precision for crisp, controlled linework",
    "From rough sketch to polished, studio-grade finish",
    "Built for manga artists, character designers and concept illustrators",
  ],
  "perfectFor": ["Manga artists", "Character designers", "Concept illustrators", "Ink artists"],
  "tags": ["liner", "marker", "ink", "inking", "manga", "fine liner", "pen"],
  "related": ["essential-line-art-sketch-kit", "master-line-art-vault-300", "free-fine-liner-brushes-100", "anime-soft-style-studio-kit"],
  "seoTitle": "39 High-Fidelity Liner & Marker Brushes for Procreate | DigiKitPro",
  "seoDesc": "39 liner & marker brushes for Procreate: technical-pen precision plus wet marker saturation for manga, character and concept art — $5.00.",
  "featured": 0
},
"a1gOh": {
  "name": "Professional Charcoal Studio for Procreate",
  "category": "Traditional",
  "assets": "Authentic charcoal brush set",
  "short": "Raw carbon, deep blacks and real paper tooth — charcoal brushes with the crumbly, smudgy energy of the traditional medium.",
  "features": [
    "True charcoal behavior: grit, deep blacks, organic smudge",
    "Real paper tooth — not soft grey 'fake charcoal' brushes",
    "Visceral, tactile blending for expressive figure work",
    "Ideal for life drawing, dramatic portraits and value studies",
  ],
  "perfectFor": ["Figure artists", "Portrait artists", "Traditional media lovers", "Value studies"],
  "tags": ["charcoal", "traditional", "graphite", "smudge", "life drawing", "sketch", "carbon"],
  "related": ["pro-sketch-traditional-art-kit", "sketchbook-traditional-media-kit", "dreamy-pastel-art-kit", "male-pose-brushes-figure-drawing"],
  "seoTitle": "Professional Charcoal Studio for Procreate — Authentic Textures | DigiKitPro",
  "seoDesc": "Authentic Procreate charcoal brushes with real carbon grit, deep blacks & paper tooth for expressive drawing and value studies — $5.00.",
  "featured": 0
},
"foZi0": {
  "name": "Male Pose Procreate Brushes — Figure Drawing Stamps",
  "category": "Figure Drawing",
  "assets": "Male pose stamp set",
  "short": "Ready-to-use male pose stamps for accurate anatomy and dynamic figure compositions in minutes, directly inside Procreate.",
  "features": [
    "Clean, ready-to-use male pose stamps",
    "Solves proportion and balance struggles fast",
    "Skip the slow sketching phase, start refining immediately",
    "For character art, illustration and figure studies",
  ],
  "perfectFor": ["Character artists", "Illustrators", "Figure drawing students", "Comic artists"],
  "tags": ["male pose", "figure drawing", "anatomy", "pose stamps", "stamps", "proportions", "body"],
  "related": ["female-pose-brushes-figure-drawing", "professional-charcoal-studio", "essential-line-art-sketch-kit", "artista-studio-kit-76-brushes"],
  "seoTitle": "Male Pose Procreate Brushes — Figure Drawing Stamp Set | DigiKitPro",
  "seoDesc": "Professional male pose stamps for Procreate: build accurate anatomy and dynamic figures in minutes on iPad. Instant .brushset download — $5.00.",
  "featured": 0
},
"8o651": {
  "name": "Female Pose Procreate Brushes — Figure Drawing Stamps",
  "category": "Figure Drawing",
  "assets": "Female pose stamp set",
  "short": "Dynamic female pose stamps for strong anatomy and balanced figures — for characters, covers, social artwork and KDP interiors.",
  "features": [
    "Accurate, dynamic female figure stamps",
    "Skip time-consuming sketching, move straight to styling",
    "Strong anatomy and balanced poses out of the box",
    "For characters, book covers, social media art and KDP interiors",
  ],
  "perfectFor": ["Character artists", "Illustrators", "Cover designers", "KDP creators"],
  "tags": ["female pose", "figure drawing", "anatomy", "pose stamps", "stamps", "proportions", "body"],
  "related": ["male-pose-brushes-figure-drawing", "hair-hairstyle-stamp-kit", "artista-studio-kit-76-brushes", "essential-line-art-sketch-kit"],
  "seoTitle": "Female Pose Procreate Brushes — Figure Drawing Stamp Set | DigiKitPro",
  "seoDesc": "Dynamic female pose stamps for Procreate: accurate anatomy and balanced figures in minutes for characters, covers & KDP interiors — $5.00.",
  "featured": 0
},
"anHCt": {
  "name": "650 Procreate Brushes Mega Bundle",
  "category": "Bundles",
  "badge": "Save 80%+",
  "assets": "650+ brushes + paper textures",
  "short": "Every DigiKitPro brush in one legendary mega kit: 650+ brushes and paper textures covering every style — at over 80% off separate prices.",
  "features": [
    "650+ highest-quality brushes plus paper textures in one download",
    "Saves over 80% versus buying every set separately",
    "Covers every style: portrait, line art, watercolor, anime, effects and more",
    "Designed by experienced artists who use these brushes daily",
  ],
  "perfectFor": ["All iPad artists", "Studios", "Artists who want one complete library"],
  "tags": ["mega bundle", "650", "all brushes", "complete library", "value", "every style"],
  "related": ["master-vault-1000-brushes", "master-library-2000-brushes", "ultimate-portrait-mastery-bundle", "artista-studio-kit-76-brushes"],
  "seoTitle": "650 Procreate Brushes Mega Bundle — Every Style, One Kit | DigiKitPro",
  "seoDesc": "650+ Procreate brushes & paper textures in one mega bundle — portrait, line art, watercolor, anime & effects. Save 80%+. Instant download — $20.00.",
  "featured": 0
},
"MChnB": {
  "name": "The Dreamy Pastel Art Kit for Procreate",
  "category": "Traditional",
  "assets": "Pastel brush set",
  "short": "Soft, grainy, nostalgic pastel brushes that bring the organic texture and effortless blending of real pastels to your iPad.",
  "features": [
    "True pastel grain — no more flat, plastic digital color",
    "Effortless blending for soft, dreamy transitions",
    "For cozy lofi illustration, dreamy portraits and soft landscapes",
    "Nostalgic traditional feel with digital convenience",
  ],
  "perfectFor": ["Lofi & cozy illustrators", "Portrait artists", "Landscape artists", "Pastel lovers"],
  "tags": ["pastel", "traditional", "lofi", "soft", "grainy", "dreamy", "blending"],
  "related": ["anime-soft-style-studio-kit", "watercolor-studio-kit-50-brushes", "pro-sketch-traditional-art-kit", "professional-charcoal-studio"],
  "seoTitle": "The Dreamy Pastel Art Kit for Procreate | DigiKitPro",
  "seoDesc": "Dreamy pastel brushes for Procreate: soft grain, organic texture & effortless blending for cozy lofi art, portraits and landscapes — $5.00.",
  "featured": 0
},
}
