#!/usr/bin/env python3
"""Individual product pages."""
import re
from core import *

def _demote_headings(htmlsrc):
    """h2->h3, h1->h3 inside shop copy (page already has h1/h2 structure)."""
    htmlsrc = re.sub(r"<h2(\s[^>]*)?>", r"<h3\1>", htmlsrc or "", flags=re.I)
    htmlsrc = re.sub(r"</h2>", "</h3>", htmlsrc, flags=re.I)
    htmlsrc = re.sub(r"<h1(\s[^>]*)?>", r"<h3\1>", htmlsrc, flags=re.I)
    htmlsrc = re.sub(r"</h1>", "</h3>", htmlsrc, flags=re.I)
    return htmlsrc

def gallery_html(p):
    im = p["images"]
    slug = p["slug"]
    main = im["main"]
    # Prefer the record's alt text: it is hand written for most products and
    # generated by tools/seo_engine.py for the rest. Falls back to the name.
    alt_main = p.get("alt") or p["name"]
    items = [(main, im.get("fullW"), im.get("fullH"), alt_main)]
    for g in im.get("gallery", []):
        items.append((g["file"], g.get("w"), g.get("h"), f'{alt_main}: preview {len(items)}'))
    if not items: return "", ""
    first = items[0]
    srcset = img_srcset(2, slug, im, "(min-width: 960px) 46vw, 100vw")
    # Pinterest: the gallery is the artwork, so it is the best thing to pin.
    # Every image carries its own data-pin-media (exact file Pinterest should
    # pull) while the description/URL always point at this product page.
    pin_page = absurl(f"products/{slug}/")
    pin_d = pin_desc(p)
    main_pin_media = asset_abs(slug, first[0])
    main_fig = f"""<figure class="gal-main">
      <img data-gal-main src="{asset_file(2, slug, first[0])}"{srcset} width="{first[1] or 1200}" height="{first[2] or 800}" alt="{esc(first[3])}" fetchpriority="high" decoding="async" data-pin-description="{esc(pin_d)}" data-pin-url="{esc(pin_page)}" data-pin-media="{esc(main_pin_media)}">
      {f'<a class="pin-btn pin-btn-gal" data-pin-anchor href="{esc(pin_create_url(pin_page, main_pin_media, pin_d))}" target="_blank" rel="noopener" aria-label="Save {esc(p["name"])} on Pinterest"><span aria-hidden="true">📌</span> Save</a>' if PINTEREST_URL else ''}
    </figure>"""
    thumbs = ""
    if len(items) > 1:
        btns = []
        for i, (f, w, h, alt) in enumerate(items):
            g = next((x for x in ([{"file": main, "card": im.get("card")}] + im.get("gallery", [])) if x["file"] == f), None)
            th = g.get("card", f) if g else f
            btns.append(f'<button class="gal-thumb{" active" if i==0 else ""}" type="button" data-gal-thumb data-full="{asset_file(2, slug, f)}" data-alt="{esc(alt)}" data-w="{w or 1200}" data-h="{h or 800}" data-pin-media="{esc(asset_abs(slug, f))}" aria-label="View image {i+1}"><img src="{asset_file(2, slug, th)}" width="{g.get("cardW") or 150}" height="{g.get("cardH") or 100}" alt="{esc(alt)} thumbnail" loading="lazy" decoding="async"></button>')
        thumbs = f'<div class="gal-thumbs">{"".join(btns)}</div>'
    return main_fig + thumbs, (first[0] if is_abs(first[0]) else absurl(f"assets/products/{slug}/{first[0]}"))

def look_inside_masterclass(p):
    """'Look Inside the Masterclass' — placeholder until 4 real interior images are supplied.

    The section is rendered for the Masterclass ebook only. It deliberately shows NO generated
    screenshots, no fake page numbers, no invented spreads: 4 labelled placeholders that 
    will be replaced by the actual PDF page exports the owner provides.
    """
    if p.get("slug") != "procreate-portrait-masterclass-ebook":
        return ""
    placeholders = "".join(
        f'<figure class="look-card look-ph" aria-label="Look inside page {i}"><div class="look-ph-box"><span>Interior page {i} — real image coming soon</span></div><figcaption>Page {i}: authentic spread will appear here</figcaption></figure>'
        for i in (1, 2, 3, 4))
    return f"""<section class="psec look-inside" id="look-inside" aria-labelledby="p-look">
      <h2 id="p-look">Look Inside the Masterclass</h2>
      <p class="muted">A complete portrait workflow in 107 pages and 15 chapters — educational PDF eBook, not a brush pack. These 4 interior spreads are placeholders for the real page images you will supply; we do not generate fake screenshots.</p>
      <div class="look-grid">{placeholders}</div>
      <p class="muted look-note"><b>No brush installation is required.</b> The Masterclass teaches with Procreate's built-in brushes; DigiKitPro kits are optional accelerators. <a href="../../blog/how-to-install-procreate-brushes/">How to install brush kits →</a></p>
    </section>"""


def workflow_strip(p):
    """Workflow positioning for key portrait kits: the order you actually paint in.

    Only rendered for the Portrait Mastery Kit and the portrait bundle, where the
    kit list already maps to a workflow (Sketch → Ink → Blend → Hair …). Keeps
    the catalog's useful-but-affordable positioning without inventing brushes.
    """
    workflow = {
        "portrait-mastery-kit-46-brushes": ["Sketch", "Ink", "Blend", "Skin", "Hair", "Detail", "Texture", "Finish"],
        "ultimate-portrait-mastery-bundle": ["Line", "Skin", "Hair", "Finish"],
        "portrait-skin-brushes-procreate": ["Blend", "Pores", "Freckles", "Texture", "Finish"],
    }.get(p.get("slug"))
    if not workflow:
        return ""
    chips = "".join(f'<span class="wf-step">{esc(s)}</span><span class="wf-arrow" aria-hidden="true">→</span>' for s in workflow[:-1]) + f'<span class="wf-step">{esc(workflow[-1])}</span>'
    return f"""<section class="psec workflow-sec" aria-labelledby="p-workflow">
      <h2 id="p-workflow">Workflow</h2>
      <p class="muted">Organized by how you actually paint — less hunting, more creating.</p>
      <div class="workflow-row">{chips}</div>
    </section>"""


def faq_html(p):
    if not p.get("faqs"): return ""
    items = "".join(f"""<details class="faq-item">
      <summary>{esc(f['q'])}</summary>
      <div class="faq-body"><p>{esc(f['a'])}</p></div>
    </details>""" for f in p["faqs"])
    return f"""<section class="psec" aria-labelledby="p-faq"><h2 id="p-faq">FAQ</h2>{items}</section>"""

def li_block(title, items, cls="check"):
    if not items: return ""
    lis = "".join(f"<li>{esc(i)}</li>" for i in items)
    tid = re.sub(r"[^a-z0-9]+", "-", title.lower())
    return f"""<section class="psec" aria-labelledby="p-{tid}"><h2 id="p-{tid}">{esc(title)}</h2><ul class="tick-list {cls}">{lis}</ul></section>"""

_ZIP_PART = re.compile(r"ZIP\s*\(\s*([\d.]+)\s*(MB|GB)\s*\)", re.I)


def collapse_zip_chain(value):
    """Summarise a long "ZIP (109MB) + ZIP (181MB) + ..." download chain.

    The Master Library lists its download as 14 chained ZIP parts, which renders
    as a 201-character unreadable run-on in the spec table. Collapse it to
    "14 ZIP files (2.2 GB total)".

    The total is SUMMED from the sizes actually listed, never estimated: if the
    parts cannot all be parsed, the original string is returned untouched.
    """
    parts = _ZIP_PART.findall(value or "")
    # Only collapse a genuine chain; 1-2 parts are perfectly readable as-is.
    if len(parts) < 3:
        return value
    # Every "+"-joined segment must be a parsed ZIP part, otherwise we would be
    # silently dropping information (e.g. "+ PDF guide") from the spec.
    segments = [s for s in re.split(r"\s*\+\s*", value.strip()) if s]
    if len(segments) != len(parts):
        return value
    total_mb = 0.0
    for size, unit in parts:
        mb = float(size) * (1024.0 if unit.upper() == "GB" else 1.0)
        total_mb += mb
    if total_mb >= 1024:
        total = f"{total_mb / 1024:.1f} GB"
    else:
        total = f"{total_mb:.0f} MB"
    return f"{len(parts)} ZIP files ({total} total)"


def tech_block(p):
    """Technical Details as a key/value spec table (colon items become rows)."""
    items = p.get("technical")
    if not items: return ""
    rows = ""
    for i in items:
        k, sep, v = i.partition(":")
        if sep and v.strip():
            v = collapse_zip_chain(v.strip())
            rows += f"<tr><th>{esc(k.strip())}</th><td>{esc(v.strip())}</td></tr>\n"
        else:
            rows += f'<tr><td colspan="2">{esc(i)}</td></tr>\n'
    return ("""<section class="psec" aria-labelledby="p-tech">"""
            """<h2 id="p-tech">Technical Details</h2>"""
            f'<table class="spec-table">{rows}</table></section>')

# ── data hygiene ────────────────────────────────────────────────────────
# Some scraped `requirements` lists have marketing lines mixed in with the
# actual requirements, which rendered on the live product page as requirements
# reading "Bring Your Portraits to Life" and "Instant Download". Filter them
# out here rather than editing data/products.json, because payhip_sync.py
# rewrites that file and any hand fix would be lost on the next sync.
_REQ_NOISE = re.compile(
    r"^(bring your|create artwork|download today|instant download|lifetime access|"
    r"\d+ premium|download today and start|start painting)", re.I)

def clean_requirements(p):
    """Keep only lines that are genuinely a requirement or a compatibility fact."""
    out, seen = [], set()
    for r in (p.get("requirements") or []):
        t = str(r).strip()
        if not t or len(t) > 140:
            continue
        if _REQ_NOISE.match(t):
            continue
        low = t.lower().rstrip(".")
        if low in seen:
            continue
        seen.add(low)
        out.append(t)
    # A product with nothing left still needs to state its platform honestly.
    if not out:
        cat = p.get("category", "")
        out = ["See the technical details below"] if cat in ("Other", "Guides & eBooks") \
              else ["iPad", "Procreate app"]
    return out


def build_product_pages():
    for p in PRODUCTS:
        slug = p["slug"]; depth = 2
        im = p["images"]
        gal, og_img = gallery_html(p)
        cslug = CATEGORY_SLUGS.get(p.get("category"))
        crumb_items = [("Home","/"),("Products","/products.html")]
        visual_crumbs = [("Products","products.html")]
        if cslug:
            crumb_items.append((p["category"], f"/category/{cslug}/"))
            visual_crumbs.append((p["category"], f"category/{cslug}/"))
        elif p.get("category") == "Bundles":
            crumb_items.append(("Bundles", "/bundles.html"))
            visual_crumbs.append(("Bundles", "bundles.html"))
        crumb_items.append((p["name"], f"/products/{slug}/"))
        visual_crumbs.append((p["name"], f"products/{slug}/"))

        schemas = schema_product(p) + schema_breadcrumb(crumb_items)
        schemas += [{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":f["q"],"acceptedAnswer":{"@type":"Answer","text":f["a"]}} for f in p.get("faqs",[])]}] if p.get("faqs") else schemas

        href_cc = f'https://creativecommons.org'
        features = li_block("Why You'll Love It", p.get("features"), cls="gold")
        included = li_block("What's Included", p.get("included"))
        technical = "" if p["slug"] == "master-library-2000-brushes" else tech_block(p)
        requirements = li_block("Requirements", clean_requirements(p), cls="plain")
        whofor = ""
        if p.get("perfectFor"):
            chips = "".join(f'<span class="tag">{esc(t)}</span>' for t in p["perfectFor"])
            whofor = f"""<section class="psec" aria-labelledby="p-for"><h2 id="p-for">Who It's For</h2><div class="tag-row">{chips}</div></section>"""
        desc = _demote_headings(p.get("descriptionHtml", ""))
        if p["slug"] == "procreate-mega-bundle-650" and not desc.strip():
            desc = "<p>650 pro Procreate brushes in one organized mega bundle. Portrait, skin, line art, watercolor and anime — every core style, instant download.</p>"
        desc_sec = f"""<section class="psec richtext" aria-labelledby="p-about"><h2 id="p-about">About This Product</h2><div class="prose">{desc}</div></section>""" if desc.strip() else ""

        bundle_block = ""
        if p.get("bundleContents"):
            rows = "".join(f'<li><span>{esc(b["name"])}</span><span class="muted">{esc(b["count"])}</span></li>' for b in p["bundleContents"])
            bundle_block = f"""<section class="psec" aria-labelledby="p-bundle"><h2 id="p-bundle">Inside the Bundle</h2><ul class="bundle-list">{rows}</ul></section>"""

        related = [BY_SLUG[r] for r in p.get("related", []) if r in BY_SLUG] or [x for x in PRODUCTS if x["category"] == p["category"] and x["slug"] != slug][:4]
        related = related[:4]
        rel_grid = product_grid(related, depth)

        # related guides (articles that teach with this product)
        try:
            arts = [a for a in load_articles() if slug in (a.get("products") or [])]
        except NameError:
            arts = []
        rel_arts = ""
        if arts:
            links = "".join(f'<a class="text-link" href="../../blog/{a["slug"]}/">{esc(a["title"])}</a>' for a in arts[:4])
            rel_arts = f"""<section class="psec" aria-labelledby="p-guides">
      <div class="sec-head"><div><p class="eyebrow">Learn the technique</p><h2 id="p-guides">Related Guides</h2></div></div>
      <div class="rel-arts">{links}</div>
    </section>"""

        # Share row: the artwork is already on the page, so a visitor can pin it
        # to their own board in one click. Placed after the guides, before the
        # closing CTA, so it never pushes the buy panel down.
        share_row = share_buttons(absurl(f"products/{slug}/"), p["name"],
                                  asset_abs(slug, im.get("main") or im.get("card", "")),
                                  pin_desc(p), heading="Save or share this artwork")

        coming = bool(p.get("comingSoon"))
        # CTA verbs are standardised site-wide: free -> "Get Free",
        # paid -> "Buy Now" (this page IS the detail page, so the button
        # goes straight to Payhip).
        cta_label = "View on Store" if coming else ("Get Free" if p["free"] else "Buy Now")
        price_html = '<span class="price price-free">Free</span>' if p["free"] else f'<span class="price price-lg">{p["priceText"]}</span>'
        if coming:
            price_html += '<span class="price-note muted"> · at launch</span>'
        if coming:
            badge = '<span class="badge badge-soon">Coming Soon</span>'
        else:
            _blabel = badge_text(p)
            badge = f'<span class="badge">{esc(_blabel)}</span>' if _blabel and not p["free"] else ('<span class="badge badge-free">Free</span>' if p["free"] else "")
        trust_items = (["Launches soon, right here on Payhip", "Newsletter subscribers get it first", "Procreate on iPad recommended"]
                       if coming else
                       ["Instant download via Payhip", "Lifetime access",
                        'Procreate on iPad required' if p['category'] not in ('Other', 'Guides & eBooks') else 'See requirements below'])
        trust = "".join(f"<li>{t}</li>" for t in trust_items)
        get_copy = ("Launches soon on our Payhip store. Join the newsletter below and you will be the first to know."
                    if coming else "Secure checkout on Payhip. Instant delivery to your email.")

        # badge chips row (status - assets - category), like the reference design
        status_chip = ('<span class="meta-chip soon">Coming Soon</span>' if coming else
                       ('<span class="meta-chip free">Free</span>' if p["free"] else
                        (f'<span class="meta-chip gold">{esc(badge_text(p))}</span>' if badge_text(p) else "")))
        assets_chip = f'<span class="meta-chip">{esc(p["assets"])}</span>' if p.get("assets") else ""
        cslug = CATEGORY_SLUGS.get(p.get("category"))
        cat_href = f"../../category/{cslug}/" if cslug else (f"../../bundles.html" if p.get("category") == "Bundles" else f"../../products.html#cat-{p['category'].replace(' ', '%20')}")
        cat_chip = f'<a class="meta-chip cat" href="{cat_href}">{esc(p["category"])}</a>'
        chips_html = status_chip + assets_chip + cat_chip
        caption = ("Launches soon · Newsletter subscribers get it first · Opens the store in a new tab"
                   if coming else "Opens the Payhip checkout in a new tab")
        cta_label_long = cta_label
        # The trust bridge (checkout + delivery + refund terms, wording taken
        # from refunds.html) replaces the old generic caption line.
        bridge = "" if coming else trust_bridge(depth, free=bool(p.get("free")))
        buy_panel = f"""<div class="buy-panel">
          <div class="buy-top"><span class="buy-label">Price</span>{price_html}</div>
          <a class="btn btn-gold btn-lg" href="{p['payhipUrl']}" target="_blank" rel="noopener" {buy_attrs(p, 'pdp-buy-panel')}>{cta_label_long} <span class="btn-arr">↗</span></a>
          <p class="buy-cap">{caption}</p>
          {bridge}
        </div>"""
        # The licence question ("can I sell what I make?") is a real purchase
        # objection for working artists. It was only answered inside a collapsed
        # FAQ and on terms.html, i.e. below the fold and hidden. Now it sits
        # under the buy panel, stating exactly what terms.html already says.
        licence = "" if coming else licence_line(p)

        _og_img = asset_abs(slug, im.get("card", "")) if im.get("card", "") else absurl("assets/img/og-cover.jpg")
        _preload = asset_abs(slug, im.get("main", "")) if im.get("main", "") else None
        html_out = head(p["seoTitle"], p["seoDesc"], absurl(f"products/{slug}/"), depth,
                        schemas=schemas, og_image=_og_img, page_type="product", preload=_preload,
                        ctx=page_ctx("product", p))
        html_out += header(depth, active="products.html")
        html_out += f"""
<main id="main">
  <div class="wrap">
    {crumbs(depth, visual_crumbs)}
    <article class="pdp">
      <div class="pdp-media">{gal}</div>
      <div class="pdp-info">
        <div class="chip-row">{chips_html}</div>
        <h1>{esc(p['name'])}</h1>
        <p class="pdp-short">{esc(p['short'])}</p>
        {buy_panel}
        {licence}
        <ul class="pdp-trust">{trust}</ul>
      </div>
    </article>

    {features}
    {bundle_block}
    {included}
    {desc_sec}
    {look_inside_masterclass(p)}
    {technical}
    {requirements}
    {install_steps(p) if not coming and not p.get("free") else ""}
    {whofor}
    {workflow_strip(p)}
    {upgrade_panel(p, depth)}
    {faq_html(p)}
    {rel_arts}
    {share_row}

    <section class="psec pdp-cta" aria-labelledby="p-get">
      <div>
        <h2 id="p-get">Get This Product</h2>
        <p class="muted">{get_copy}</p>
        {"" if coming else trust_bridge(depth, free=bool(p.get("free")))}
      </div>
      <a class="btn btn-gold btn-lg" href="{p['payhipUrl']}" target="_blank" rel="noopener" {buy_attrs(p, 'pdp-bottom')}>{cta_label} <span class="btn-arr">↗</span></a>
    </section>

    <section class="psec" aria-labelledby="p-related">
      <div class="sec-head"><div><p class="eyebrow">You may also like</p><h2 id="p-related">Related Products</h2></div></div>
      {rel_grid}
    </section>
  </div>
  {newsletter(depth)}
</main>
"""
        html_out += footer(depth)
        write(f"products/{slug}/index.html", html_out)

# category landing stub pages for breadcrumbs/SEO (products.html handles filtering)
